<h1><center>Laboratorio 9: Optimización de modelos 💯</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2024</strong></center>

### **Cuerpo Docente:**

- Profesores: Ignacio Meza, Sebastián Tinoco
- Auxiliar: Eduardo Moya
- Ayudantes: Nicolás Ojeda, Melanie Peña, Valentina Rojas

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Damián De Aguiar
- Nombre de alumno 2: Angelo León

### **Link de repositorio de GitHub:** [Insertar Repositorio](https://github.com/damiatus/labPrograCientifica)

### Temas a tratar

- Predicción de demanda usando `xgboost`
- Búsqueda del modelo óptimo de clasificación usando `optuna`
- Uso de pipelines.

### Reglas:

- **Grupos de 2 personas**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias.
- Pueden usar cualquer matrial del curso que estimen conveniente.
- Código que no se pueda ejecutar, no será revisado.

### Objetivos principales del laboratorio

- Optimizar modelos usando `optuna`
- Recurrir a técnicas de *prunning*
- Forzar el aprendizaje de relaciones entre variables mediante *constraints*
- Fijar un pipeline con un modelo base que luego se irá optimizando.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre DataFrames.

# Importamos librerias útiles

In [1]:
#!pip install -qq xgboost optuna

print('jola')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.8/362.8 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.2/233.2 kB 15.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 5.5 MB/s eta 0:00:00
jola

# El emprendimiento de Fiu

Tras liderar de manera exitosa la implementación de un proyecto de ciencia de datos para caracterizar los datos generados en Santiago 2023, el misterioso corpóreo **Fiu** se anima y decide levantar su propio negocio de consultoría en machine learning. Tras varias e intensas negociaciones, Fiu logra encontrar su *primera chamba*: predecir la demanda (cantidad de venta) de una famosa productora de bebidas de calibre mundial. Al ver el gran potencial y talento que usted ha demostrado en el campo de la ciencia de datos, Fiu lo contrata como data scientist para que forme parte de su nuevo emprendimiento.

Para este laboratorio deben trabajar con los datos `sales.csv` subidos a u-cursos, el cual contiene una muestra de ventas de la empresa para diferentes productos en un determinado tiempo.

Para comenzar, cargue el dataset señalado y visualice a través de un `.head` los atributos que posee el dataset.

<i><p align="center">Fiu siendo felicitado por su excelente desempeño en el proyecto de caracterización de datos</p></i>
<p align="center">
  <img src="https://media-front.elmostrador.cl/2023/09/A_UNO_1506411_2440e.jpg">
</p>

In [35]:
import pandas as pd
import numpy as np
from datetime import datetime

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import FunctionTransformer, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error
import xgboost as xgb
import joblib

from sklearn.preprocessing import StandardScaler, OneHotEncoder

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [48]:
file_path = '/content/drive/My Drive/LabdeProgra/Lab9'
df = pd.read_csv(file_path + "/sales.csv")
df.head()

,id,date,city,lat,long,pop,shop,brand,container,capacity,price,quantity
0,0,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,glass,500ml,0.96,13280
1,1,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,plastic,1.5lt,2.86,6727
2,2,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,can,330ml,0.87,9848
3,3,31/01/12,Athens,37.97945,23.71622,672130,shop_1,adult-cola,glass,500ml,1.00,20050
4,4,31/01/12,Athens,37.97945,23.71622,672130,shop_1,adult-cola,can,330ml,0.39,25696

## 1 Generando un Baseline (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/O-lan6TkadUAAAAC/what-i-wnna-do-after-a-baseline.gif">
</p>

Antes de entrenar un algoritmo, usted recuerda los apuntes de su magíster en ciencia de datos y recuerda que debe seguir una serie de *buenas prácticas* para entrenar correcta y debidamente su modelo. Después de un par de vueltas, llega a las siguientes tareas:

1. Separe los datos en conjuntos de train (70%), validation (20%) y test (10%). Fije una semilla para controlar la aleatoriedad. [0.5 puntos]
2. Implemente un `FunctionTransformer` para extraer el día, mes y año de la variable `date`. Guarde estas variables en el formato categorical de pandas. [1 punto]
3. Implemente un `ColumnTransformer` para procesar de manera adecuada los datos numéricos y categóricos. Use `OneHotEncoder` para las variables categóricas. `Nota:` Utilice el método `.set_output(transform='pandas')` para obtener un DataFrame como salida del `ColumnTransformer` [1 punto]
4. Guarde los pasos anteriores en un `Pipeline`, dejando como último paso el regresor `DummyRegressor` para generar predicciones en base a promedios. [0.5 punto]
5. Entrene el pipeline anterior y reporte la métrica `mean_absolute_error` sobre los datos de validación. ¿Cómo se interpreta esta métrica para el contexto del negocio? [0.5 puntos]
6. Finalmente, vuelva a entrenar el `Pipeline` pero esta vez usando `XGBRegressor` como modelo **utilizando los parámetros por default**. ¿Cómo cambia el MAE al implementar este algoritmo? ¿Es mejor o peor que el `DummyRegressor`? [1 punto]
7. Guarde ambos modelos en un archivo .pkl (uno cada uno) [0.5 puntos]

In [49]:
#1:
from sklearn import set_config

set_config(transform_output="pandas")

train_data, temp_data = train_test_split(df, test_size=0.3, random_state=20676305)
val_data, test_data = train_test_split(temp_data, test_size=0.33, random_state=20676305)

X_train = train_data.drop(columns=['quantity'])
y_train = train_data['quantity']

X_val = val_data.drop(columns=['quantity'])
y_val = val_data['quantity']

X_test = test_data.drop(columns=['quantity'])
y_test = test_data['quantity']

print(f"Train size: {train_data.shape}, Validation size: {val_data.shape}, Test size: {test_data.shape}")

Train size: (5219, 12), Validation size: (1498, 12), Test size: (739, 12)

In [50]:
# 2:

def extract_date_features(df):
    df['year'] = pd.to_datetime(df['date'], format='%d/%m/%y').dt.year
    df['month'] = pd.to_datetime(df['date'], format='%d/%m/%y').dt.month
    df['day'] = pd.to_datetime(df['date'], format='%d/%m/%y').dt.day

    df['year'] = df['year'].astype('category')
    df['month'] = df['month'].astype('category')
    df['day'] = df['day'].astype('category')
    return df.drop(columns=['date'])


date_transformer = FunctionTransformer(extract_date_features)

In [25]:
df.nunique()

id           7456
date           84
city            5
lat             6
long            6
pop            35
shop            6
brand           5
container       3
capacity        3
price         402
quantity     6906
year            7
month          12
day             4
dtype: int64

Al analizar los valores únicos vemos que las variables que no son categoricas son: 'lat', 'long', 'pop', 'price', 'quantity'

In [57]:
df

,id,date,city,lat,long,pop,shop,brand,container,capacity,price,quantity
0,0,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,glass,500ml,0.96,13280
1,1,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,plastic,1.5lt,2.86,6727
2,2,31/01/12,Athens,37.97945,23.71622,672130,shop_1,kinder-cola,can,330ml,0.87,9848
3,3,31/01/12,Athens,37.97945,23.71622,672130,shop_1,adult-cola,glass,500ml,1.00,20050
4,4,31/01/12,Athens,37.97945,23.71622,672130,shop_1,adult-cola,can,330ml,0.39,25696
...,...,...,...,...,...,...,...,...,...,...,...,...
7451,7555,31/12/18,Athens,37.97945,23.71622,664046,shop_1,kinder-cola,plastic,1.5lt,2.52,13760
7452,7556,31/12/18,Athens,37.97945,23.71622,664046,shop_1,orange-power,plastic,1.5lt,2.18,16309
7453,7557,31/12/18,Patra,38.24444,21.73444,168034,shop_6,kinder-cola,can,330ml,0.85,24378
7454,7558,31/12/18,Thessaloniki,40.64361,22.93086,354290,shop_4,adult-cola,plastic,1.5lt,2.17,20691
7455,7559,31/12/18,Irakleion,35.32787,25.14341,137154,shop_2,adult-cola,glass,500ml,1.26,24615

In [51]:
# 3:

num_features = ['lat', 'long', 'pop', 'price']
cat_features = ['city', 'shop', 'year', 'month', 'day']

numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, num_features),
        ('cat', categorical_transformer, cat_features)
    ]
)

In [52]:
# 4 y 5:

pipeline_dummy = Pipeline(steps=[
    ('date_extractor', date_transformer),
    ('preprocessor', preprocessor),
    ('regressor', DummyRegressor(strategy="mean"))
])

pipeline_dummy.fit(X_train, y_train)
y_val_pred = pipeline_dummy.predict(X_val)

mae_dummy = mean_absolute_error(y_val, y_val_pred)
print(f'MAE en validación con DummyRegressor: {mae_dummy}')

MAE en validación con DummyRegressor: 13270.306990274572

El MAE reportado es e 13.270,30; eso quiere decir que las prediciones del modelo utilizado poseen un error medio absoluto de tal valor. Como la unidad que se esta prediciendo es en cantidades, el error tambien posee dicha unidad, que es una de las caracteristicas del MAE.

Crear el Pipeline con DummyRegressor

In [53]:
# 6:

pipeline_xgb = Pipeline(steps=[
    ('date_extractor', date_transformer),
    ('preprocessor', preprocessor),
    ('regressor', xgb.XGBRegressor())
])

pipeline_xgb.fit(X_train, y_train)
y_val_pred_xgb = pipeline_xgb.predict(X_val)

mae_xgb = mean_absolute_error(y_val, y_val_pred_xgb)
print(f'MAE en validación con XGBRegressor: {mae_xgb}')

MAE en validación con XGBRegressor: 7002.643389428092

Dado que el MAE es el error medio que tiene el model0 entrenado, mientras menor sea, es un indicio de que el modelo es mejor. Dicho esto, como el MAE de XGBRegressor es menor a DummyRegressor, el modelo es mejor.

In [56]:
# 7:
import pickle

with open(file_path + '/pipeline_dummy.pkl', 'wb') as f:
    pickle.dump(pipeline_dummy, f)

with open(file_path + '/pipeline_xgb.pkl', 'wb') as f:
    pickle.dump(pipeline_xgb, f)

## 2. Forzando relaciones entre parámetros con XGBoost (10 puntos)

<p align="center">
  <img src="https://64.media.tumblr.com/14cc45f9610a6ee341a45fd0d68f4dde/20d11b36022bca7b-bf/s640x960/67ab1db12ff73a530f649ac455c000945d99c0d6.gif">
</p>

Un colega aficionado a la economía le *sopla* que la demanda guarda una relación inversa con el precio del producto. Motivado para impresionar al querido corpóreo, se propone hacer uso de esta información para mejorar su modelo realizando las siguientes tareas:

1. Vuelva a entrenar el `Pipeline` con `XGBRegressor`, pero esta vez forzando una relación monótona negativa entre el precio y la cantidad. Para aplicar esta restricción apóyese en la siguiente <a href = https://xgboost.readthedocs.io/en/stable/tutorials/monotonic.html>documentación</a>. [6 puntos]

>Hint 1: Para implementar el constraint se le sugiere hacerlo especificando el nombre de la variable. De ser así, probablemente le sea útil **mantener el formato de pandas** antes del step de entrenamiento.

>Hint 2: Puede obtener el nombre de las columnas en el paso anterior al modelo regresor mediante el método `.get_feature_names_out()`

2. Luego, vuelva a reportar el `MAE` sobre el conjunto de validación. [1 puntos]

3. ¿Cómo cambia el error al incluir esta relación? ¿Tenía razón su amigo? [2 puntos]

4. Guarde su modelo en un archivo .pkl [1 punto]

In [64]:
#1:

preprocessor.fit(X_train)
feature_names = preprocessor.get_feature_names_out()

monotone_constraints = {name: 0 for name in feature_names}
monotone_constraints["num__price"] = -1

pipeline_xgb_monotonic = Pipeline(steps=[
    ('date_extractor', date_transformer),
    ('preprocessor', preprocessor),
    ('regressor', xgb.XGBRegressor(monotone_constraints=monotone_constraints))
])

pipeline_xgb_monotonic.fit(X_train, y_train)

Pipeline(steps=[('date_extractor',
                 FunctionTransformer(func=<function extract_date_features at 0x7fe92cfc7010>)),
                ('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['lat', 'long', 'pop',
                                                   'price']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['city', 'shop', 'year',
                                                   'month', 'day'])])),
                ('regressor',
                 XGBRegressor(base_s...
                                                    'cat__month_6': 0,
                                                    'cat__month_7': 0,
                                                    'cat__month_8': 0,
                                                    'cat__month_9': 0,
                                                    'cat__shop_shop_1': 0,
                                                    'cat__shop_shop_2': 0,
                                                    'cat__shop_shop_3': 0,
                                                    'cat__shop_shop_4': 0,
                                                    'cat__shop_shop_5': 0,
                                                    'cat__shop_shop_6': 0,
                                                    'cat__year_2012': 0,
                                                    'cat__year_2013': 0,
                                                    'cat__year_2014': 0, ...},
                              multi_strategy=None, n_estimators=None,
                              n_jobs=None, num_parallel_tree=None,
                              random_state=None, ...))])

In [65]:
#2:
y_val_pred_monotonic = pipeline_xgb_monotonic.predict(X_val)
mae_monotonic = mean_absolute_error(y_val, y_val_pred_monotonic)

print(f'MAE en validación con XGBRegressor (monotonía negativa): {mae_monotonic}')

MAE en validación con XGBRegressor (monotonía negativa): 7289.645706375387

In [69]:
#3:

print(f'MAE anterior: {mae_xgb}')
print(f'MAE con XGBRegressor y restricción: {mae_monotonic}')

MAE anterior: 7002.643389428092
MAE con XGBRegressor y restricción: 7289.645706375387

Dado los resultados, se puede decir que mi amigo no tenia razon, ya que el nuevo MAE es mayor al anterior, lo que quiere decir que el modelo posee un error medio mayor que el anterior modelo.

In [70]:
#4:

with open(file_path + '/pipeline_xgb_monotonic.pkl', 'wb') as f:
    pickle.dump(pipeline_xgb_monotonic, f)

## 1.3 Optimización de Hiperparámetros con Optuna (20 puntos)

<p align="center">
  <img src="https://media.tenor.com/fmNdyGN4z5kAAAAi/hacking-lucy.gif">
</p>

Luego de presentarle sus resultados, Fiu le pregunta si es posible mejorar *aun más* su modelo. En particular, le comenta de la optimización de hiperparámetros con metodologías bayesianas a través del paquete `optuna`. Como usted es un aficionado al entrenamiento de modelos de ML, se propone implementar la descabellada idea de su jefe.

A partir de la mejor configuración obtenida en la sección anterior, utilice `optuna` para optimizar sus hiperparámetros. En particular, se pide que su optimización considere lo siguiente:

- Fijar una semilla en las instancias necesarias para garantizar la reproducibilidad de resultados
- Utilice `TPESampler` como método de muestreo
- De `XGBRegressor`, optimice los siguientes hiperparámetros:
    - `learning_rate` buscando valores flotantes en el rango (0.001, 0.1)
    - `n_estimators` buscando valores enteros en el rango (50, 1000)
    - `max_depth` buscando valores enteros en el rango (3, 10)
    - `max_leaves` buscando valores enteros en el rango (0, 100)
    - `min_child_weight` buscando valores enteros en el rango (1, 5)
    - `reg_alpha` buscando valores flotantes en el rango (0, 1)
    - `reg_lambda` buscando valores flotantes en el rango (0, 1)
- De `OneHotEncoder`, optimice el hiperparámetro `min_frequency` buscando el mejor valor flotante en el rango (0.0, 1.0)

Para ello se pide los siguientes pasos:
1. Implemente una función `objective()` que permita minimizar el `MAE` en el conjunto de validación. Use el método `.set_user_attr()` para almacenar el mejor pipeline entrenado. [10 puntos]
2. Fije el tiempo de entrenamiento a 5 minutos. [1 punto]
3. Optimizar el modelo y reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
4. Explique cada hiperparámetro y su rol en el modelo. ¿Hacen sentido los rangos de optimización indicados? [5 puntos]
5. Guardar su modelo en un archivo .pkl [1 punto]

In [135]:
import optuna
from optuna.samplers import TPESampler
optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective(trial):
    learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
    n_estimators = trial.suggest_int("n_estimators", 50, 1000)
    max_depth = trial.suggest_int("max_depth", 3, 10)
    max_leaves = trial.suggest_int("max_leaves", 0, 100)
    min_child_weight = trial.suggest_int("min_child_weight", 1, 5)
    reg_alpha = trial.suggest_float("reg_alpha", 0, 1)
    reg_lambda = trial.suggest_float("reg_lambda", 0, 1)
    min_frequency = trial.suggest_float("min_frequency", 0.0, 1.0)

    one_hot_encoder = OneHotEncoder(min_frequency=min_frequency, sparse_output=False)

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', 'passthrough', num_features),
            ('cat', one_hot_encoder, cat_features)
        ],
        remainder='drop'
    )

    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('regressor', xgb.XGBRegressor(
            learning_rate=learning_rate,
            n_estimators=n_estimators,
            max_depth=max_depth,
            max_leaves=max_leaves,
            min_child_weight=min_child_weight,
            reg_alpha=reg_alpha,
            reg_lambda=reg_lambda,
            random_state=20676305
        ))
    ])

    pipeline.fit(X_train, y_train)

    y_val_pred = pipeline.predict(X_val)
    mae = mean_absolute_error(y_val, y_val_pred)
    if "best_mae" not in study.user_attrs or mae < study.user_attrs["best_mae"]:
        study.set_user_attr("best_mae", mae)
        study.set_user_attr("best_pipeline", pipeline)

    return mae

In [136]:
#2:

study = optuna.create_study(sampler=TPESampler(), direction='minimize')
study.optimize(objective, timeout=300)

In [137]:
#3:

print(f'Número de trials: {len(study.trials)}')
print(f'MAE: {study.best_value}')
print(f'Mejores hiperparámetros: {study.best_params}')

Número de trials: 372
MAE: 6455.685521613454
Mejores hiperparámetros: {'learning_rate': 0.06088478489392484, 'n_estimators': 542, 'max_depth': 4, 'max_leaves': 6, 'min_child_weight': 3, 'reg_alpha': 0.7741164547571104, 'reg_lambda': 0.20572736310470496, 'min_frequency': 0.02018803593966867}

Comparando los modelos anteriores con este nuevo que fue optimizado mediante Optuna sus hiperparametros, se puede decir que los resultados, medidos en el MAE, son mejores que los anteriores modelos. Esta mejora se debe a la optimizacion producida, al probar los distintos hiperparametros, esto provoca que los modelos posean mejores resultados.

4: Hiperparametros.

Hiperparámetros de XGBRegressor

- learning_rate: Parámetro controla la contribución de cada árbol al modelo final. Un valor más bajo significa que el modelo necesita más árboles para lograr la misma precisión, pero puede llevar a un modelo más robusto y menos propenso a sobreajustarse.

- n_estimators: Define el número total de árboles que se construirán en el modelo. Un número mayor puede aumentar el rendimiento, pero también puede llevar a un sobreajuste.

- max_depth: Determina la profundidad máxima de cada árbol. Árboles más profundos pueden capturar patrones complejos en los datos, pero también son más propensos a sobreajustarse. Se ajusta este parámetro para encontrar un balance entre sesgo y varianza.

- max_leaves: Establece el número máximo de hojas que se pueden crear en cada árbol. Limitar las hojas puede ayudar a reducir la complejidad del modelo y evitar el sobreajuste.

- min_child_weight: Define el peso mínimo de la suma de instancias en un nodo hijo. Valores más altos previenen la creación de nodos que contienen pocos ejemplos, ayudando a controlar el sobreajuste.

- reg_alpha: Regularización L1. Penaliza la complejidad del modelo. Un valor mayor puede ayudar a reducir el sobreajuste al obligar al modelo a aprender representaciones más simples.

- reg_lambda: Regularización L2. Similar a reg_alpha, pero la regularización L2 penaliza más fuertemente los pesos grandes en el modelo, lo que también puede ayudar a prevenir el sobreajuste.

Hiperparámetro de OneHotEncoder:

- min_frequency: Define la frecuencia mínima requerida para que una categoría se incluya en el conjunto de datos transformado. Si una categoría aparece menos veces que el valor especificado, se agrupa en una categoría "poco frecuente". Puede ser útil para reducir la dimensionalidad y prevenir el sobreajuste.

In [138]:
#5:

best_pipeline = study.user_attrs["best_pipeline"]
with open(file_path + '/best_xgb_pipeline.pkl', 'wb') as f:
    pickle.dump(best_pipeline, f)

## 4. Optimización de Hiperparámetros con Optuna y Prunners (17 puntos)

<p align="center">
  <img src="https://i.pinimg.com/originals/90/16/f9/9016f919c2259f3d0e8fe465049638a7.gif">
</p>

Después de optimizar el rendimiento de su modelo varias veces, Fiu le pregunta si no es posible optimizar el entrenamiento del modelo en sí mismo. Después de leer un par de post de personas de dudosa reputación en la *deepweb*, usted llega a la conclusión que puede cumplir este objetivo mediante la implementación de **Prunning**.

Vuelva a optimizar los mismos hiperparámetros que la sección pasada, pero esta vez utilizando **Prunning** en la optimización. En particular, usted debe:

- Responder: ¿Qué es prunning? ¿De qué forma debería impactar en el entrenamiento? [2 puntos]
- Redefinir la función `objective()` utilizando `optuna.integration.XGBoostPruningCallback` como método de **Prunning** [10 puntos]
- Fijar nuevamente el tiempo de entrenamiento a 5 minutos [1 punto]
- Reportar el número de *trials*, el `MAE` y los mejores hiperparámetros encontrados. ¿Cómo cambian sus resultados con respecto a la sección anterior? ¿A qué se puede deber esto? [3 puntos]
- Guardar su modelo en un archivo .pkl [1 punto]

Nota: Si quieren silenciar los prints obtenidos en el prunning, pueden hacerlo mediante el siguiente comando:

```
optuna.logging.set_verbosity(optuna.logging.WARNING)
```

De implementar la opción anterior, pueden especificar `show_progress_bar = True` en el método `optimize` para *más sabor*.

Hint: Si quieren especificar parámetros del método .fit() del modelo a través del pipeline, pueden hacerlo por medio de la siguiente sintaxis: `pipeline.fit(stepmodelo__parametro = valor)`

Hint2: Este <a href = https://stackoverflow.com/questions/40329576/sklearn-pass-fit-parameters-to-xgboost-in-pipeline>enlace</a> les puede ser de ayuda en su implementación

In [89]:
#!pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.10/dist-packages (from optuna-integration[xgboost]) (4.0.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (from optuna-integration[xgboost]) (2.1.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from optuna->optuna-integration[xgboost]) (1.13.3)
Requirement already satisfied: colorlog in /usr/local/lib/python3.10/dist-packages (from optuna->optuna-integration[xgboost]) (6.8.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna->optuna-integration[xgboost]) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna->optuna-integration[xgboost]) (24.1)
Requirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.36)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna->optuna-integration[xgboost]) (4.66.5)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.10/dist-packages (from xgboost->optuna-integration[xgboost]) (2.23.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost->optuna-integration[xgboost]) (1.13.1)
Requirement already satisfied: Mako in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.6)
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.3.0->optuna->optuna-integration[xgboost]) (3.1.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.2)
Downloading optuna_integration-4.0.0-py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 2.0 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.0.0

1: El prunning es una tecnica usada en la optimizacion de hiperparametros, con el enfoque de parar el entrenamiento del modelo si no hay mejorias en sus resultados. Esta tecnica posee como objetivo ahorrar recursos computacionales y reducir los tiempos de optimizacion de hiperparametros.

In [130]:
#2:

from optuna.integration import XGBoostPruningCallback
optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective2(trial):
    learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
    n_estimators = trial.suggest_int("n_estimators", 50, 1000)
    max_depth = trial.suggest_int("max_depth", 3, 10)
    max_leaves = trial.suggest_int("max_leaves", 0, 100)
    min_child_weight = trial.suggest_int("min_child_weight", 1, 5)
    reg_alpha = trial.suggest_float("reg_alpha", 0, 1)
    reg_lambda = trial.suggest_float("reg_lambda", 0, 1)
    min_frequency = trial.suggest_float("min_frequency", 0.0, 1.0)

    one_hot_encoder = OneHotEncoder(min_frequency=min_frequency, sparse_output=False)

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', 'passthrough', num_features),
            ('cat', one_hot_encoder, cat_features)
        ],
        remainder='drop'
    )

    X_train_transformed = preprocessor.fit_transform(X_train)
    X_val_transformed = preprocessor.transform(X_val)

    dtrain = xgb.DMatrix(X_train_transformed, label=y_train)
    dval = xgb.DMatrix(X_val_transformed, label=y_val)

    params = {
        'learning_rate': learning_rate,
        'max_depth': max_depth,
        'max_leaves': max_leaves,
        'min_child_weight': min_child_weight,
        'reg_alpha': reg_alpha,
        'reg_lambda': reg_lambda,
        'objective': 'reg:squarederror',
        'eval_metric': 'mae',
        'random_state': 20676305
    }

    model = xgb.train(
        params,
        dtrain,
        evals=[(dval, 'validation')],
        callbacks=[XGBoostPruningCallback(trial, observation_key='validation-mae')]
    )

    y_val_pred = model.predict(dval)
    mae = mean_absolute_error(y_val, y_val_pred)
    trial.report(mae, step=1)

    if trial.should_prune():
        raise optuna.TrialPruned()

    if "best_mae" not in study.user_attrs or mae < study.user_attrs["best_mae"]:
        study.set_user_attr("best_mae", mae)
        study.set_user_attr("best_pipeline", model)

    return mae

In [131]:
#3:

study = optuna.create_study(sampler=optuna.samplers.TPESampler(), direction='minimize')
study.optimize(objective2, timeout=300, show_progress_bar=True)

   0%|          | 00:00/05:00

[0]	validation-mae:13165.97187
[1]	validation-mae:13063.99593
[2]	validation-mae:12964.68292
[3]	validation-mae:12867.17973
[4]	validation-mae:12771.93425
[5]	validation-mae:12679.67755
[6]	validation-mae:12589.49453
[7]	validation-mae:12501.16954
[8]	validation-mae:12415.75645
[9]	validation-mae:12332.05000

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:13242.56970
[1]	validation-mae:13214.93281
[2]	validation-mae:13187.40374
[3]	validation-mae:13160.00397
[4]	validation-mae:13132.72814
[5]	validation-mae:13105.71719
[6]	validation-mae:13079.18700
[7]	validation-mae:13052.93078
[8]	validation-mae:13026.76051
[9]	validation-mae:13000.93780
[0]	validation-mae:13252.34074
[1]	validation-mae:13234.43055
[2]	validation-mae:13216.57751
[3]	validation-mae:13198.84799
[4]	validation-mae:13181.10459
[5]	validation-mae:13163.50939
[6]	validation-mae:13145.91212

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[7]	validation-mae:13128.51394
[8]	validation-mae:13111.11613
[9]	validation-mae:13093.98015
[0]	validation-mae:13101.69088
[1]	validation-mae:12939.58691
[2]	validation-mae:12785.16074
[3]	validation-mae:12635.00150
[4]	validation-mae:12490.12536
[5]	validation-mae:12351.59489
[6]	validation-mae:12218.44628
[7]	validation-mae:12091.03355
[8]	validation-mae:11966.06352
[9]	validation-mae:11846.04769

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12601.87578
[1]	validation-mae:12044.10445
[2]	validation-mae:11559.62905
[3]	validation-mae:11147.07700
[4]	validation-mae:10787.10031
[5]	validation-mae:10471.12230
[6]	validation-mae:10215.32854

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[7]	validation-mae:9992.10614
[8]	validation-mae:9792.37853
[9]	validation-mae:9628.39637
[0]	validation-mae:12737.28561
[1]	validation-mae:12275.40202
[2]	validation-mae:11862.65930
[3]	validation-mae:11487.03035
[4]	validation-mae:11166.30513
[5]	validation-mae:10877.07421

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[6]	validation-mae:10608.46325
[7]	validation-mae:10379.36871
[8]	validation-mae:10171.65400
[9]	validation-mae:10001.08797

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:13087.48644
[1]	validation-mae:12912.31623
[2]	validation-mae:12745.59691
[3]	validation-mae:12586.00125
[4]	validation-mae:12432.11076
[5]	validation-mae:12285.62399
[6]	validation-mae:12143.85992
[7]	validation-mae:12004.34909
[8]	validation-mae:11873.66731
[9]	validation-mae:11746.72656
[0]	validation-mae:12472.00773
[1]	validation-mae:11796.42502
[2]	validation-mae:11220.03399

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[3]	validation-mae:10732.30506
[4]	validation-mae:10306.02708
[5]	validation-mae:9939.30151
[6]	validation-mae:9638.59361
[7]	validation-mae:9396.43175
[8]	validation-mae:9178.43712
[9]	validation-mae:9003.20497
[0]	validation-mae:12907.62239
[1]	validation-mae:12576.33678
[2]	validation-mae:12278.15817
[3]	validation-mae:12015.99649
[4]	validation-mae:11766.39064
[5]	validation-mae:11537.03813
[6]	validation-mae:11321.45914
[7]	validation-mae:11127.22853

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[8]	validation-mae:10944.83340
[9]	validation-mae:10781.99561

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12449.50401
[1]	validation-mae:11762.57700
[2]	validation-mae:11168.40678
[3]	validation-mae:10657.34387
[4]	validation-mae:10195.69433
[5]	validation-mae:9797.64168
[6]	validation-mae:9448.28801
[7]	validation-mae:9137.32352
[8]	validation-mae:8862.52259
[9]	validation-mae:8628.31897

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12448.38150
[1]	validation-mae:11759.86340
[2]	validation-mae:11164.55194
[3]	validation-mae:10652.62626
[4]	validation-mae:10190.43694
[5]	validation-mae:9793.24265
[6]	validation-mae:9443.57398
[7]	validation-mae:9136.23546
[8]	validation-mae:8849.88402
[9]	validation-mae:8628.71654

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12689.22393
[1]	validation-mae:12189.62902
[2]	validation-mae:11745.13533
[3]	validation-mae:11351.68935
[4]	validation-mae:11007.68457
[5]	validation-mae:10701.93149
[6]	validation-mae:10433.47714
[7]	validation-mae:10210.33081
[8]	validation-mae:10014.63353
[9]	validation-mae:9843.08377

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12903.80885
[0]	validation-mae:12534.33737
[1]	validation-mae:11916.03848
[2]	validation-mae:11394.36950
[3]	validation-mae:10954.53778
[4]	validation-mae:10573.39440
[5]	validation-mae:10262.35245
[6]	validation-mae:10002.48075
[7]	validation-mae:9781.07069
[8]	validation-mae:9586.43564
[9]	validation-mae:9426.31567

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12658.51156
[1]	validation-mae:12133.13096
[2]	validation-mae:11676.75926
[3]	validation-mae:11268.95974
[4]	validation-mae:10917.99863
[5]	validation-mae:10589.56582
[6]	validation-mae:10293.05693
[7]	validation-mae:10048.99762
[8]	validation-mae:9815.52548
[9]	validation-mae:9610.11910

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12724.56179
[0]	validation-mae:12563.20736
[1]	validation-mae:11959.48117
[2]	validation-mae:11429.46685
[3]	validation-mae:10969.68790
[4]	validation-mae:10556.78149
[5]	validation-mae:10208.47935
[6]	validation-mae:9910.94500
[7]	validation-mae:9646.36484
[8]	validation-mae:9422.82905
[9]	validation-mae:9233.19653
[0]	validation-mae:12448.56556
[1]	validation-mae:11753.67665
[2]	validation-mae:11169.78789
[3]	validation-mae:10641.30081

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[4]	validation-mae:10189.05388
[5]	validation-mae:9798.24524
[6]	validation-mae:9460.47475
[7]	validation-mae:9152.98585
[8]	validation-mae:8910.20337
[9]	validation-mae:8666.64991
[0]	validation-mae:12495.00373
[1]	validation-mae:11845.85863

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[2]	validation-mae:11291.84883
[3]	validation-mae:10813.79720
[4]	validation-mae:10391.56171
[5]	validation-mae:10033.19901
[6]	validation-mae:9743.06315
[7]	validation-mae:9496.69346
[8]	validation-mae:9287.82913
[9]	validation-mae:9106.02835
[0]	validation-mae:12621.30239
[1]	validation-mae:12056.80457

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[2]	validation-mae:11556.23368
[3]	validation-mae:11113.90972
[4]	validation-mae:10721.82071
[5]	validation-mae:10387.56863
[6]	validation-mae:10084.68433
[7]	validation-mae:9826.65998
[8]	validation-mae:9611.36137
[9]	validation-mae:9418.39282

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12597.77305
[1]	validation-mae:12051.03816
[2]	validation-mae:11575.96938
[3]	validation-mae:11154.39293
[4]	validation-mae:10793.76664
[5]	validation-mae:10460.93854
[6]	validation-mae:10174.85987
[7]	validation-mae:9923.30736
[8]	validation-mae:9680.17299
[9]	validation-mae:9485.58734

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12554.66422
[1]	validation-mae:11992.02149
[2]	validation-mae:11490.87312
[3]	validation-mae:11048.66421
[4]	validation-mae:10671.75989
[5]	validation-mae:10333.33175
[6]	validation-mae:10031.10220
[7]	validation-mae:9781.44697
[8]	validation-mae:9563.54910
[9]	validation-mae:9373.68726
[0]	validation-mae:12496.53495
[1]	validation-mae:11827.97004
[2]	validation-mae:11245.94269
[3]	validation-mae:10768.76852
[4]	validation-mae:10316.23177
[5]	validation-mae:9919.14965
[6]	validation-mae:9573.10241
[7]	validation-mae:9265.13613

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[8]	validation-mae:9001.59599
[9]	validation-mae:8765.36537
[0]	validation-mae:12665.70622

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12493.94271
[1]	validation-mae:11827.38821
[2]	validation-mae:11248.30305
[3]	validation-mae:10754.76118
[4]	validation-mae:10311.15593
[5]	validation-mae:9931.65825
[6]	validation-mae:9584.43226
[7]	validation-mae:9255.00351
[8]	validation-mae:8977.91155
[9]	validation-mae:8752.22827
[0]	validation-mae:12604.04220

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12527.12135
[1]	validation-mae:11896.10638
[2]	validation-mae:11342.47964
[3]	validation-mae:10879.11672
[4]	validation-mae:10468.56577
[5]	validation-mae:10114.55150
[6]	validation-mae:9805.23474
[7]	validation-mae:9540.92604
[8]	validation-mae:9325.82973
[9]	validation-mae:9134.24430
[0]	validation-mae:12539.65262
[1]	validation-mae:11921.26217
[2]	validation-mae:11402.36508
[3]	validation-mae:10928.09712
[4]	validation-mae:10497.80773
[5]	validation-mae:10119.27598
[6]	validation-mae:9781.67073

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[7]	validation-mae:9488.25668
[8]	validation-mae:9212.20938
[9]	validation-mae:8977.69702
[0]	validation-mae:12590.12397

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12487.62660
[1]	validation-mae:11838.55463
[2]	validation-mae:11274.85950
[3]	validation-mae:10792.49775
[4]	validation-mae:10374.22914
[5]	validation-mae:10020.99537
[6]	validation-mae:9717.80410
[7]	validation-mae:9462.91949
[8]	validation-mae:9249.70969
[9]	validation-mae:9050.63527
[0]	validation-mae:12779.84367

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12546.22936
[1]	validation-mae:11941.34380
[2]	validation-mae:11442.60546
[3]	validation-mae:11002.28556
[4]	validation-mae:10633.36774
[5]	validation-mae:10310.09497
[6]	validation-mae:10039.50247
[0]	validation-mae:12647.97220
[0]	validation-mae:12504.92922
[1]	validation-mae:11846.34717
[2]	validation-mae:11271.81741
[3]	validation-mae:10795.72476
[4]	validation-mae:10351.83253
[5]	validation-mae:9969.66678
[6]	validation-mae:9620.41825
[7]	validation-mae:9303.97503
[8]	validation-mae:9026.54707
[9]	validation-mae:8800.50717
[0]	validation-mae:12525.24628
[1]	validation-mae:11877.17994
[2]	validation-mae:11318.33680
[3]	validation-mae:10833.99889
[4]	validation-mae:10391.82684
[5]	validation-mae:10019.35533
[6]	validation-mae:9686.02866
[7]	validation-mae:9379.99165

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[8]	validation-mae:9098.41771
[9]	validation-mae:8861.71604

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12498.50010
[1]	validation-mae:11848.63210
[2]	validation-mae:11296.68001
[3]	validation-mae:10825.46646
[4]	validation-mae:10398.35320
[5]	validation-mae:10037.35799
[6]	validation-mae:9735.64599
[7]	validation-mae:9480.91411
[8]	validation-mae:9268.39947
[9]	validation-mae:9074.45238

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12523.70472
[1]	validation-mae:11913.95698
[2]	validation-mae:11386.44013
[3]	validation-mae:10925.42771
[4]	validation-mae:10542.66640
[5]	validation-mae:10223.97433
[6]	validation-mae:9968.12180
[0]	validation-mae:13049.38034
[0]	validation-mae:12499.71131
[1]	validation-mae:11833.38392
[2]	validation-mae:11259.41591
[3]	validation-mae:10777.40684
[4]	validation-mae:10339.04902
[5]	validation-mae:9951.38876
[6]	validation-mae:9602.99576
[7]	validation-mae:9288.02157
[8]	validation-mae:9010.06924
[9]	validation-mae:8765.14508
[0]	validation-mae:12463.17528
[1]	validation-mae:11776.44685
[2]	validation-mae:11169.61895

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[3]	validation-mae:10666.29226
[4]	validation-mae:10220.09826
[5]	validation-mae:9833.01977
[6]	validation-mae:9487.22234
[7]	validation-mae:9178.96729
[8]	validation-mae:8905.33779
[9]	validation-mae:8670.92390

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12461.24416
[1]	validation-mae:11775.18078
[2]	validation-mae:11183.33101
[3]	validation-mae:10676.28280
[4]	validation-mae:10229.13167
[5]	validation-mae:9825.50385
[6]	validation-mae:9467.66856
[7]	validation-mae:9170.96354
[8]	validation-mae:8897.79338
[9]	validation-mae:8661.37506
[0]	validation-mae:12494.63350
[1]	validation-mae:11825.71431
[2]	validation-mae:11257.83250

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[3]	validation-mae:10770.20536
[4]	validation-mae:10346.98812
[5]	validation-mae:9995.77255
[6]	validation-mae:9696.31379
[7]	validation-mae:9434.67928
[8]	validation-mae:9210.08315
[9]	validation-mae:9012.68581
[0]	validation-mae:12472.85065
[1]	validation-mae:11803.26948
[2]	validation-mae:11209.90825

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[3]	validation-mae:10715.21337
[4]	validation-mae:10285.33159
[5]	validation-mae:9894.87592
[6]	validation-mae:9533.67426
[7]	validation-mae:9231.71208
[8]	validation-mae:8939.88028
[9]	validation-mae:8710.01866
[0]	validation-mae:12468.78613
[1]	validation-mae:11794.17562
[2]	validation-mae:11204.43178

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[3]	validation-mae:10695.86449
[4]	validation-mae:10251.71568
[5]	validation-mae:9870.81882
[6]	validation-mae:9532.85260
[7]	validation-mae:9230.33292
[8]	validation-mae:8952.68095
[9]	validation-mae:8700.14579

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12848.06268
[0]	validation-mae:12573.94502
[0]	validation-mae:12472.75319
[1]	validation-mae:11799.82941
[2]	validation-mae:11209.55454
[3]	validation-mae:10717.99340
[4]	validation-mae:10287.30446
[5]	validation-mae:9894.79600
[6]	validation-mae:9536.10532
[7]	validation-mae:9233.42276
[8]	validation-mae:8951.36282
[9]	validation-mae:8720.91830
[0]	validation-mae:12492.02433

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11822.29894
[2]	validation-mae:11248.04981
[3]	validation-mae:10755.40512
[4]	validation-mae:10324.44849
[5]	validation-mae:9931.71357
[6]	validation-mae:9575.78742
[7]	validation-mae:9268.28423
[8]	validation-mae:8988.35656
[9]	validation-mae:8744.17119
[0]	validation-mae:12557.24651

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12455.11421
[1]	validation-mae:11760.39361
[2]	validation-mae:11165.60611
[3]	validation-mae:10651.19375
[4]	validation-mae:10207.49120
[5]	validation-mae:9803.48677
[6]	validation-mae:9451.31638
[7]	validation-mae:9143.69244
[8]	validation-mae:8880.20310
[9]	validation-mae:8636.11098

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12474.18566
[1]	validation-mae:11814.48733
[2]	validation-mae:11235.98623
[3]	validation-mae:10752.71087
[4]	validation-mae:10340.13552
[5]	validation-mae:9989.58811
[6]	validation-mae:9685.28345
[7]	validation-mae:9436.55493
[8]	validation-mae:9220.55787
[9]	validation-mae:9036.52299

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12573.80190
[0]	validation-mae:12469.75610
[1]	validation-mae:11806.90381
[2]	validation-mae:11225.76947
[3]	validation-mae:10724.96505
[4]	validation-mae:10313.87081
[5]	validation-mae:9950.81864
[6]	validation-mae:9643.04280
[7]	validation-mae:9385.80979
[8]	validation-mae:9158.89893
[9]	validation-mae:8980.69974

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12672.77008
[0]	validation-mae:12465.21005
[1]	validation-mae:11792.18313
[2]	validation-mae:11201.76371
[3]	validation-mae:10688.74318
[4]	validation-mae:10216.79639
[5]	validation-mae:9816.01170
[6]	validation-mae:9467.77014
[7]	validation-mae:9166.62944
[8]	validation-mae:8898.05253
[9]	validation-mae:8655.68477

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12471.44595
[1]	validation-mae:11789.58319
[2]	validation-mae:11207.39926
[3]	validation-mae:10703.67831
[4]	validation-mae:10256.14719
[5]	validation-mae:9865.10264
[6]	validation-mae:9521.90322
[7]	validation-mae:9210.95443
[8]	validation-mae:8946.84162
[9]	validation-mae:8687.28100

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12498.38276
[1]	validation-mae:11837.94074
[2]	validation-mae:11274.33808
[3]	validation-mae:10780.95463
[4]	validation-mae:10350.10500
[5]	validation-mae:9957.55870
[6]	validation-mae:9615.46695
[7]	validation-mae:9301.90730
[8]	validation-mae:9022.17628
[9]	validation-mae:8770.77152

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12520.50322
[0]	validation-mae:12472.04316
[1]	validation-mae:11797.98488
[2]	validation-mae:11211.52269
[3]	validation-mae:10708.07043
[4]	validation-mae:10268.95437
[5]	validation-mae:9872.82114
[6]	validation-mae:9519.21864
[7]	validation-mae:9217.52274
[8]	validation-mae:8946.68450
[9]	validation-mae:8718.78951
[0]	validation-mae:12578.40017

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12463.63188
[1]	validation-mae:11788.05971
[2]	validation-mae:11199.53898
[3]	validation-mae:10673.73330
[4]	validation-mae:10215.31860
[5]	validation-mae:9812.99257
[6]	validation-mae:9458.96584
[7]	validation-mae:9150.67876
[8]	validation-mae:8892.30655
[9]	validation-mae:8660.77486
[0]	validation-mae:12444.96122

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11758.73614
[2]	validation-mae:11153.14419
[3]	validation-mae:10637.04376
[4]	validation-mae:10189.03685
[5]	validation-mae:9788.12483
[6]	validation-mae:9422.43169
[7]	validation-mae:9110.15551
[8]	validation-mae:8854.83070
[9]	validation-mae:8602.95257
[0]	validation-mae:12439.80020
[1]	validation-mae:11751.77208

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[2]	validation-mae:11144.16176
[3]	validation-mae:10626.09901
[4]	validation-mae:10175.95699
[5]	validation-mae:9775.67907
[6]	validation-mae:9410.99328
[7]	validation-mae:9089.05177
[8]	validation-mae:8842.78096
[9]	validation-mae:8578.24439

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12439.03619
[1]	validation-mae:11748.61477
[2]	validation-mae:11142.37793
[3]	validation-mae:10624.58422
[4]	validation-mae:10176.30147
[5]	validation-mae:9756.50694
[6]	validation-mae:9395.34750
[7]	validation-mae:9082.00636
[8]	validation-mae:8827.33752
[9]	validation-mae:8592.81880
[0]	validation-mae:12414.30588
[1]	validation-mae:11718.00627

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[2]	validation-mae:11100.73000
[3]	validation-mae:10557.27377
[4]	validation-mae:10098.66020
[5]	validation-mae:9670.95020
[6]	validation-mae:9304.86777
[7]	validation-mae:9008.09664
[8]	validation-mae:8733.54806
[9]	validation-mae:8505.12696

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12464.66725
[1]	validation-mae:11793.53615
[2]	validation-mae:11187.90927
[3]	validation-mae:10665.71498
[4]	validation-mae:10202.47096
[5]	validation-mae:9796.13813
[6]	validation-mae:9449.53337
[7]	validation-mae:9154.86381
[8]	validation-mae:8891.55645
[9]	validation-mae:8631.67047

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:13191.22111
[0]	validation-mae:12409.38818
[1]	validation-mae:11688.00317
[2]	validation-mae:11059.19916
[3]	validation-mae:10521.11657
[4]	validation-mae:10029.52483
[5]	validation-mae:9627.48113
[6]	validation-mae:9273.99478
[7]	validation-mae:8978.31418
[8]	validation-mae:8703.68629
[9]	validation-mae:8462.43618
[0]	validation-mae:12418.40306
[1]	validation-mae:11703.99929
[2]	validation-mae:11082.62948
[3]	validation-mae:10547.53942
[4]	validation-mae:10059.55324

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[5]	validation-mae:9664.36331
[6]	validation-mae:9315.06893
[7]	validation-mae:9012.11105
[8]	validation-mae:8732.76501
[9]	validation-mae:8497.27500
[0]	validation-mae:12511.40787

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.28027
[1]	validation-mae:11709.23149
[2]	validation-mae:11080.69132
[3]	validation-mae:10540.46675
[4]	validation-mae:10051.00557
[5]	validation-mae:9639.99204
[6]	validation-mae:9275.39558
[7]	validation-mae:8967.82177
[8]	validation-mae:8700.51068
[9]	validation-mae:8444.17325
[0]	validation-mae:12421.06711

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11707.70579
[2]	validation-mae:11086.53876
[3]	validation-mae:10552.96725
[4]	validation-mae:10064.46903
[5]	validation-mae:9670.33973
[6]	validation-mae:9319.90883
[7]	validation-mae:9008.41803
[8]	validation-mae:8737.18624
[9]	validation-mae:8494.52350

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12447.64926
[1]	validation-mae:11760.43901
[2]	validation-mae:11155.10663
[3]	validation-mae:10641.54761
[4]	validation-mae:10192.66050
[5]	validation-mae:9800.37256
[6]	validation-mae:9439.97805
[7]	validation-mae:9131.75916
[8]	validation-mae:8862.16142
[9]	validation-mae:8614.48880

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12475.78558
[1]	validation-mae:11813.03335
[2]	validation-mae:11241.96349
[3]	validation-mae:10752.76061
[0]	validation-mae:12471.83467
[1]	validation-mae:11782.47652
[2]	validation-mae:11186.59170
[3]	validation-mae:10688.90002
[4]	validation-mae:10259.44812
[5]	validation-mae:9900.51995
[6]	validation-mae:9609.20661
[7]	validation-mae:9356.99680
[0]	validation-mae:12460.12573
[1]	validation-mae:11782.04172
[2]	validation-mae:11178.46703
[3]	validation-mae:10676.10829
[4]	validation-mae:10232.35879
[5]	validation-mae:9842.19628
[6]	validation-mae:9473.81225
[7]	validation-mae:9157.82425
[8]	validation-mae:8895.88993
[9]	validation-mae:8675.15843

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12458.60133
[1]	validation-mae:11779.46993
[2]	validation-mae:11175.13042
[3]	validation-mae:10662.25807
[4]	validation-mae:10224.08237
[5]	validation-mae:9835.05637
[6]	validation-mae:9470.46439
[7]	validation-mae:9164.20719
[8]	validation-mae:8894.36068
[9]	validation-mae:8646.56223

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12780.15603
[0]	validation-mae:12453.70336
[1]	validation-mae:11767.86343
[2]	validation-mae:11165.43848
[3]	validation-mae:10643.18517
[4]	validation-mae:10169.78654
[5]	validation-mae:9761.74731
[6]	validation-mae:9402.61331
[7]	validation-mae:9093.00891
[8]	validation-mae:8820.16961
[9]	validation-mae:8563.25207
[0]	validation-mae:12429.45103

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11731.47252
[2]	validation-mae:11107.37443
[3]	validation-mae:10581.11729
[4]	validation-mae:10093.30579
[5]	validation-mae:9685.30338
[6]	validation-mae:9332.89176
[7]	validation-mae:9042.30863
[8]	validation-mae:8765.60911
[9]	validation-mae:8501.29733

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12455.66210
[1]	validation-mae:11787.30512
[2]	validation-mae:11192.81407
[3]	validation-mae:10666.25503
[4]	validation-mae:10217.35903
[5]	validation-mae:9822.59169
[6]	validation-mae:9444.51113
[7]	validation-mae:9127.74733
[8]	validation-mae:8867.31176
[9]	validation-mae:8607.93517
[0]	validation-mae:12549.07957

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12895.62101
[0]	validation-mae:12412.62273
[1]	validation-mae:11704.80898
[2]	validation-mae:11071.08346
[3]	validation-mae:10536.21710
[4]	validation-mae:10046.84155
[5]	validation-mae:9638.20566
[6]	validation-mae:9263.22163
[7]	validation-mae:8963.03421
[8]	validation-mae:8695.95046
[9]	validation-mae:8437.99116
[0]	validation-mae:12454.90293
[1]	validation-mae:11776.70280
[2]	validation-mae:11169.37670
[3]	validation-mae:10648.44180
[4]	validation-mae:10184.24328

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[5]	validation-mae:9771.29432
[6]	validation-mae:9417.11018
[7]	validation-mae:9113.87488
[8]	validation-mae:8856.55284
[9]	validation-mae:8588.41869
[0]	validation-mae:12471.19506
[1]	validation-mae:11809.95673

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12467.93544
[1]	validation-mae:11796.76576
[2]	validation-mae:11202.64161
[3]	validation-mae:10687.50409
[4]	validation-mae:10241.37722
[5]	validation-mae:9823.41930
[6]	validation-mae:9475.82045
[7]	validation-mae:9170.06885
[8]	validation-mae:8891.43671
[9]	validation-mae:8658.65630

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12434.99078
[1]	validation-mae:11730.79250
[2]	validation-mae:11117.98578
[3]	validation-mae:10594.08235
[4]	validation-mae:10120.95251
[5]	validation-mae:9695.83690
[6]	validation-mae:9339.79686
[7]	validation-mae:9042.35044
[8]	validation-mae:8789.42947
[9]	validation-mae:8541.51033

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12460.22733
[1]	validation-mae:11775.26279
[2]	validation-mae:11193.65650
[3]	validation-mae:10663.13403
[4]	validation-mae:10181.10615
[5]	validation-mae:9778.96610
[6]	validation-mae:9419.10900
[7]	validation-mae:9111.77543
[8]	validation-mae:8846.66034
[9]	validation-mae:8594.21199

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12415.52943
[1]	validation-mae:11698.29752
[2]	validation-mae:11075.10858
[3]	validation-mae:10537.72373
[4]	validation-mae:10048.33090
[5]	validation-mae:9651.70118
[6]	validation-mae:9302.14491
[7]	validation-mae:8996.11468
[8]	validation-mae:8723.53043
[9]	validation-mae:8476.19564

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12417.21076
[1]	validation-mae:11700.89655
[2]	validation-mae:11078.90255
[3]	validation-mae:10542.70577
[4]	validation-mae:10053.71475
[5]	validation-mae:9657.09824
[6]	validation-mae:9307.61145
[7]	validation-mae:9001.75377
[8]	validation-mae:8727.80938
[9]	validation-mae:8479.60511

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12451.85646
[1]	validation-mae:11752.78851
[2]	validation-mae:11138.81946
[3]	validation-mae:10618.83674
[4]	validation-mae:10156.88933
[5]	validation-mae:9739.57039
[6]	validation-mae:9381.35185
[7]	validation-mae:9086.87609
[8]	validation-mae:8806.04986
[9]	validation-mae:8555.95236

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12445.78375
[1]	validation-mae:11741.95251
[2]	validation-mae:11132.34587
[3]	validation-mae:10602.85847
[4]	validation-mae:10128.99201
[5]	validation-mae:9711.72444
[6]	validation-mae:9330.82936
[7]	validation-mae:9035.76995
[8]	validation-mae:8750.36179
[9]	validation-mae:8500.76958

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12449.02244
[1]	validation-mae:11746.82690
[2]	validation-mae:11131.17535
[3]	validation-mae:10601.91320
[4]	validation-mae:10134.05587
[5]	validation-mae:9717.99184
[6]	validation-mae:9357.69659
[7]	validation-mae:9058.60021
[8]	validation-mae:8784.81330
[9]	validation-mae:8529.75896

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12416.56514
[1]	validation-mae:11690.78960
[2]	validation-mae:11063.20212
[3]	validation-mae:10529.72070
[4]	validation-mae:10051.78055
[5]	validation-mae:9619.66888
[6]	validation-mae:9260.08847
[7]	validation-mae:8961.23938
[8]	validation-mae:8685.51603
[9]	validation-mae:8429.65939

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12418.02642
[1]	validation-mae:11692.94852
[2]	validation-mae:11069.48429
[3]	validation-mae:10534.23528
[4]	validation-mae:10060.59599
[5]	validation-mae:9640.53141
[6]	validation-mae:9279.85605
[7]	validation-mae:8981.55119
[8]	validation-mae:8703.33126
[9]	validation-mae:8448.32310
[0]	validation-mae:12420.85663

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11697.85253
[2]	validation-mae:11075.28395
[3]	validation-mae:10540.87020
[4]	validation-mae:10067.81319
[5]	validation-mae:9647.53796
[6]	validation-mae:9286.51484
[7]	validation-mae:8986.72188
[8]	validation-mae:8716.59061
[9]	validation-mae:8459.00302
[0]	validation-mae:12414.76063

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11686.56901
[2]	validation-mae:11060.17680
[3]	validation-mae:10521.46388
[4]	validation-mae:10045.79853
[5]	validation-mae:9620.63145
[6]	validation-mae:9273.28345
[7]	validation-mae:8967.46353
[8]	validation-mae:8701.03706
[9]	validation-mae:8445.09578

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12433.83722
[1]	validation-mae:11723.11824
[2]	validation-mae:11099.80452
[3]	validation-mae:10563.74456
[4]	validation-mae:10092.85719
[5]	validation-mae:9671.15873
[6]	validation-mae:9322.12003
[7]	validation-mae:9014.81287
[8]	validation-mae:8745.18654
[9]	validation-mae:8494.83415

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12434.65753
[1]	validation-mae:11720.87122
[2]	validation-mae:11094.45549
[3]	validation-mae:10558.67311
[4]	validation-mae:10088.43715
[5]	validation-mae:9669.68904
[6]	validation-mae:9310.91553
[7]	validation-mae:9001.07838
[8]	validation-mae:8728.29384
[9]	validation-mae:8484.90252

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.44513
[1]	validation-mae:11690.01505
[2]	validation-mae:11065.10649
[3]	validation-mae:10527.69333
[4]	validation-mae:10053.56610
[5]	validation-mae:9621.46940
[6]	validation-mae:9274.40707
[7]	validation-mae:8970.42112
[8]	validation-mae:8702.53746
[9]	validation-mae:8439.56753

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12416.86977
[1]	validation-mae:11690.12597
[2]	validation-mae:11059.11002
[3]	validation-mae:10517.78218
[4]	validation-mae:10044.14864
[5]	validation-mae:9612.65004
[6]	validation-mae:9265.98460
[7]	validation-mae:8960.30073
[8]	validation-mae:8692.63779
[9]	validation-mae:8437.04482

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.05472
[1]	validation-mae:11690.74029
[2]	validation-mae:11064.56483
[3]	validation-mae:10521.34885
[4]	validation-mae:10041.69652
[5]	validation-mae:9615.57998
[6]	validation-mae:9259.95002
[7]	validation-mae:8965.13664
[8]	validation-mae:8702.73134
[9]	validation-mae:8445.40546
[0]	validation-mae:12418.59239

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11696.70753
[2]	validation-mae:11064.34015
[3]	validation-mae:10515.33137
[4]	validation-mae:10044.91606
[5]	validation-mae:9621.21969
[6]	validation-mae:9268.96932
[7]	validation-mae:8945.04123
[8]	validation-mae:8674.31439
[9]	validation-mae:8426.94168

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12419.16777
[1]	validation-mae:11696.35251
[2]	validation-mae:11062.43215
[3]	validation-mae:10518.70382
[4]	validation-mae:10057.41572
[5]	validation-mae:9648.12234
[6]	validation-mae:9300.34755
[7]	validation-mae:8983.52219
[8]	validation-mae:8710.88480
[9]	validation-mae:8455.04606
[0]	validation-mae:12494.33301

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12419.25016
[1]	validation-mae:11698.25292
[2]	validation-mae:11054.27695
[3]	validation-mae:10512.44557
[4]	validation-mae:10039.15874
[5]	validation-mae:9618.81382
[6]	validation-mae:9255.97538
[7]	validation-mae:8952.21198
[8]	validation-mae:8678.77477
[9]	validation-mae:8422.48059

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:13001.61157
[0]	validation-mae:12415.90809
[1]	validation-mae:11692.55520
[2]	validation-mae:11046.87239
[3]	validation-mae:10498.01350
[4]	validation-mae:10021.68085
[5]	validation-mae:9596.00516
[6]	validation-mae:9239.66642
[7]	validation-mae:8941.74687
[8]	validation-mae:8677.07472
[9]	validation-mae:8422.98560

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12416.73606
[1]	validation-mae:11694.03169
[2]	validation-mae:11048.74383
[3]	validation-mae:10500.22400
[4]	validation-mae:10019.50947
[5]	validation-mae:9595.61578
[6]	validation-mae:9241.73207
[7]	validation-mae:8934.70372
[8]	validation-mae:8666.60419
[9]	validation-mae:8402.01411

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12445.46077
[1]	validation-mae:11743.46704
[2]	validation-mae:11113.46481
[3]	validation-mae:10575.58631
[4]	validation-mae:10101.91474
[5]	validation-mae:9681.08658
[6]	validation-mae:9325.40157
[7]	validation-mae:9013.80885
[8]	validation-mae:8742.41608
[9]	validation-mae:8502.40659
[0]	validation-mae:12416.11106

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11688.26194
[2]	validation-mae:11060.76510
[3]	validation-mae:10526.38423
[4]	validation-mae:10051.08680
[5]	validation-mae:9627.26446
[6]	validation-mae:9269.89493
[7]	validation-mae:8970.53358
[8]	validation-mae:8706.76609
[9]	validation-mae:8449.81739

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12440.61887
[1]	validation-mae:11735.05186
[2]	validation-mae:11107.21671
[3]	validation-mae:10566.54118
[4]	validation-mae:10094.28306
[5]	validation-mae:9671.30313
[6]	validation-mae:9312.25416
[7]	validation-mae:8999.01504
[8]	validation-mae:8728.63203
[9]	validation-mae:8476.52938

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12412.27637
[1]	validation-mae:11686.23095
[2]	validation-mae:11061.06453
[3]	validation-mae:10528.06479
[4]	validation-mae:10044.53636
[5]	validation-mae:9615.97308
[6]	validation-mae:9268.69679
[7]	validation-mae:8956.60963
[8]	validation-mae:8688.38968
[9]	validation-mae:8453.67138

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12448.67705
[1]	validation-mae:11756.88217
[2]	validation-mae:11143.12234
[3]	validation-mae:10610.99638
[4]	validation-mae:10137.25011
[5]	validation-mae:9716.91796
[6]	validation-mae:9362.88399
[7]	validation-mae:9078.06984
[8]	validation-mae:8804.16581
[9]	validation-mae:8555.37406

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.61730
[1]	validation-mae:11687.42146
[2]	validation-mae:11051.85933
[3]	validation-mae:10518.00444
[4]	validation-mae:10039.33974
[5]	validation-mae:9611.26468
[6]	validation-mae:9257.23985
[7]	validation-mae:8952.20057
[8]	validation-mae:8695.75952
[9]	validation-mae:8455.97517
[0]	validation-mae:12414.07597

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11686.50630
[2]	validation-mae:11050.66906
[3]	validation-mae:10515.93326
[4]	validation-mae:10037.14960
[5]	validation-mae:9615.30833
[6]	validation-mae:9269.42426
[7]	validation-mae:8964.37488
[8]	validation-mae:8696.92458
[9]	validation-mae:8456.10130
[0]	validation-mae:12435.20323

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11724.32867
[2]	validation-mae:11101.82182
[3]	validation-mae:10569.01128
[4]	validation-mae:10093.90643
[5]	validation-mae:9671.45466
[6]	validation-mae:9323.03256
[7]	validation-mae:9014.90351
[8]	validation-mae:8739.77271
[9]	validation-mae:8490.83184

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12432.84972
[1]	validation-mae:11718.88249
[2]	validation-mae:11093.17931
[3]	validation-mae:10559.75046
[4]	validation-mae:10088.54055
[5]	validation-mae:9668.03911
[6]	validation-mae:9312.98614
[7]	validation-mae:9004.45738
[8]	validation-mae:8731.63702
[9]	validation-mae:8488.21955

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12448.93346
[1]	validation-mae:11747.04717
[2]	validation-mae:11129.12724
[3]	validation-mae:10602.57864
[4]	validation-mae:10131.95695
[5]	validation-mae:9710.61887
[6]	validation-mae:9359.11612
[7]	validation-mae:9061.13078
[8]	validation-mae:8792.98085
[9]	validation-mae:8543.17338

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12463.90355
[0]	validation-mae:12431.34621
[1]	validation-mae:11715.95587
[2]	validation-mae:11089.12451
[3]	validation-mae:10555.19778
[4]	validation-mae:10083.98510
[5]	validation-mae:9666.04891
[6]	validation-mae:9306.82817
[7]	validation-mae:9004.50544
[8]	validation-mae:8729.05778
[9]	validation-mae:8482.72886

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12552.15106
[0]	validation-mae:12415.51310
[1]	validation-mae:11688.97273
[2]	validation-mae:11053.83075
[3]	validation-mae:10519.67278
[4]	validation-mae:10041.25461
[5]	validation-mae:9619.53021
[6]	validation-mae:9273.69703
[7]	validation-mae:8969.15097
[8]	validation-mae:8701.52944
[9]	validation-mae:8460.86850

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12431.40013
[1]	validation-mae:11719.30699
[2]	validation-mae:11092.94954
[3]	validation-mae:10563.09449
[4]	validation-mae:10090.41530
[5]	validation-mae:9665.98693
[6]	validation-mae:9317.45392
[7]	validation-mae:9009.30513
[8]	validation-mae:8737.13974
[9]	validation-mae:8494.37566

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12447.08114
[1]	validation-mae:11743.24722
[2]	validation-mae:11124.52390
[3]	validation-mae:10596.08138
[4]	validation-mae:10124.47039
[5]	validation-mae:9708.08514
[6]	validation-mae:9357.62482
[7]	validation-mae:9059.82765
[8]	validation-mae:8790.08401
[9]	validation-mae:8534.67278

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12413.38807
[1]	validation-mae:11694.95357
[2]	validation-mae:11064.53827
[3]	validation-mae:10522.98494
[4]	validation-mae:10050.75536
[5]	validation-mae:9623.98311
[6]	validation-mae:9253.72045
[7]	validation-mae:8950.35995
[8]	validation-mae:8666.34824
[9]	validation-mae:8408.62596

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12529.24407
[0]	validation-mae:12445.72422
[1]	validation-mae:11742.39016
[2]	validation-mae:11125.15566
[3]	validation-mae:10593.88404
[4]	validation-mae:10125.44847
[5]	validation-mae:9705.71257
[6]	validation-mae:9356.56601
[7]	validation-mae:9046.84966
[8]	validation-mae:8772.03841
[9]	validation-mae:8522.11168

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.44551
[1]	validation-mae:11687.11468
[2]	validation-mae:11051.48154
[3]	validation-mae:10517.52987
[4]	validation-mae:10038.80859
[5]	validation-mae:9610.73462
[6]	validation-mae:9256.68891
[7]	validation-mae:8951.68930
[8]	validation-mae:8699.72062
[9]	validation-mae:8459.96724
[0]	validation-mae:12429.72812

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11715.79215
[2]	validation-mae:11089.45692
[3]	validation-mae:10556.55310
[4]	validation-mae:10080.49490
[5]	validation-mae:9654.42198
[6]	validation-mae:9302.11286
[7]	validation-mae:8992.16456
[8]	validation-mae:8723.04404
[9]	validation-mae:8476.95086

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12415.15405
[1]	validation-mae:11686.62814
[2]	validation-mae:11058.66307
[3]	validation-mae:10523.91873
[4]	validation-mae:10048.39810
[5]	validation-mae:9624.45809
[6]	validation-mae:9267.07787
[7]	validation-mae:8967.75672
[8]	validation-mae:8704.15485
[9]	validation-mae:8447.27989
[0]	validation-mae:12446.76366
[1]	validation-mae:11741.59799

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[2]	validation-mae:11121.29031
[3]	validation-mae:10592.36546
[4]	validation-mae:10122.35449
[5]	validation-mae:9699.68236
[6]	validation-mae:9346.83349
[7]	validation-mae:9035.05171
[8]	validation-mae:8764.82666
[9]	validation-mae:8518.04409
[0]	validation-mae:12570.68629

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12473.05592
[0]	validation-mae:12437.83115
[1]	validation-mae:11731.28761
[2]	validation-mae:11102.92934
[3]	validation-mae:10568.84286
[4]	validation-mae:10093.72910
[5]	validation-mae:9677.69498
[6]	validation-mae:9320.75829
[7]	validation-mae:9012.75690
[8]	validation-mae:8740.68751
[9]	validation-mae:8499.19789

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12412.62051
[1]	validation-mae:11688.43149
[2]	validation-mae:11064.32581
[3]	validation-mae:10531.57989
[4]	validation-mae:10045.06257
[5]	validation-mae:9613.16640
[6]	validation-mae:9263.71274
[7]	validation-mae:8951.18376
[8]	validation-mae:8682.10685
[9]	validation-mae:8435.84100

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12436.60330
[1]	validation-mae:11721.02170
[2]	validation-mae:11104.69845
[3]	validation-mae:10572.74507
[4]	validation-mae:10096.24641
[5]	validation-mae:9686.53147
[6]	validation-mae:9309.46110
[7]	validation-mae:9012.24383
[8]	validation-mae:8741.86433
[9]	validation-mae:8502.55633
[0]	validation-mae:12413.10966
[1]	validation-mae:11687.49039

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[2]	validation-mae:11062.70968
[3]	validation-mae:10530.09442
[4]	validation-mae:10044.84769
[5]	validation-mae:9613.67454
[6]	validation-mae:9266.16466
[7]	validation-mae:8970.02654
[8]	validation-mae:8706.94789
[9]	validation-mae:8460.89459
[0]	validation-mae:12445.45377
[1]	validation-mae:11741.68903

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[2]	validation-mae:11121.48985
[3]	validation-mae:10582.13827
[4]	validation-mae:10114.99123
[5]	validation-mae:9694.76557
[6]	validation-mae:9350.87706
[7]	validation-mae:9027.74795
[8]	validation-mae:8749.77192
[9]	validation-mae:8492.04439

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.39110
[1]	validation-mae:11688.76623
[2]	validation-mae:11064.34753
[3]	validation-mae:10526.01196
[4]	validation-mae:10051.10192
[5]	validation-mae:9619.47935
[6]	validation-mae:9273.34929
[7]	validation-mae:8972.50992
[8]	validation-mae:8702.98149
[9]	validation-mae:8446.92384
[0]	validation-mae:12531.22092

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.77120
[1]	validation-mae:11686.60822
[2]	validation-mae:11057.03207
[3]	validation-mae:10515.07673
[4]	validation-mae:10040.42228
[5]	validation-mae:9609.72548
[6]	validation-mae:9261.66232
[7]	validation-mae:8951.66047
[8]	validation-mae:8686.36209
[9]	validation-mae:8422.41962
[0]	validation-mae:12512.52907

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12446.00997
[1]	validation-mae:11743.65938
[2]	validation-mae:11134.03447
[3]	validation-mae:10611.26386
[4]	validation-mae:10145.52528
[5]	validation-mae:9720.35871
[6]	validation-mae:9362.76933
[7]	validation-mae:9069.98571
[8]	validation-mae:8789.40801
[9]	validation-mae:8539.58860

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12429.72491
[1]	validation-mae:11715.19889
[2]	validation-mae:11088.68184
[3]	validation-mae:10558.66667
[4]	validation-mae:10085.51857
[5]	validation-mae:9668.02781
[6]	validation-mae:9319.55532
[7]	validation-mae:9025.73484
[8]	validation-mae:8754.50262
[9]	validation-mae:8497.82473

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12427.02009
[1]	validation-mae:11711.50690
[2]	validation-mae:11079.53331
[3]	validation-mae:10539.19644
[4]	validation-mae:10069.39129
[5]	validation-mae:9646.83740
[6]	validation-mae:9296.49792
[7]	validation-mae:8971.55782
[8]	validation-mae:8699.47201
[9]	validation-mae:8453.64068
[0]	validation-mae:12428.99231
[1]	validation-mae:11714.89200
[2]	validation-mae:11084.75029

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[3]	validation-mae:10539.13737
[4]	validation-mae:10068.14219
[5]	validation-mae:9646.52564
[6]	validation-mae:9297.71100
[7]	validation-mae:8978.84778
[8]	validation-mae:8702.11013
[9]	validation-mae:8448.81339
[0]	validation-mae:12445.95672
[1]	validation-mae:11744.19729
[2]	validation-mae:11122.50334
[3]	validation-mae:10583.55933

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[4]	validation-mae:10117.38264
[5]	validation-mae:9698.06501
[6]	validation-mae:9356.98906
[7]	validation-mae:9053.59069
[8]	validation-mae:8778.43168
[9]	validation-mae:8520.45262

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12930.77066
[0]	validation-mae:12431.08330
[1]	validation-mae:11718.65631
[2]	validation-mae:11080.69983
[3]	validation-mae:10543.25508
[4]	validation-mae:10066.01684
[5]	validation-mae:9644.96633
[6]	validation-mae:9282.02232
[7]	validation-mae:8969.31344
[8]	validation-mae:8697.86737
[9]	validation-mae:8448.80916

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12459.33206
[0]	validation-mae:12446.42074
[1]	validation-mae:11740.04562
[2]	validation-mae:11116.78606
[3]	validation-mae:10589.39100
[4]	validation-mae:10116.74637
[5]	validation-mae:9699.94333
[6]	validation-mae:9349.98841
[7]	validation-mae:9036.56098
[8]	validation-mae:8756.22344
[9]	validation-mae:8505.74187

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12434.42029
[1]	validation-mae:11723.21450
[2]	validation-mae:11093.98585
[3]	validation-mae:10562.15064
[4]	validation-mae:10093.69922
[5]	validation-mae:9668.37563
[6]	validation-mae:9315.61869
[7]	validation-mae:9001.12015
[8]	validation-mae:8730.98833
[9]	validation-mae:8472.17527

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12427.44411
[1]	validation-mae:11712.31616
[2]	validation-mae:11080.45818
[3]	validation-mae:10539.42737
[4]	validation-mae:10068.81310
[5]	validation-mae:9646.65843
[6]	validation-mae:9294.89907
[7]	validation-mae:8975.90708
[8]	validation-mae:8703.33047
[9]	validation-mae:8457.44076

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12415.58135
[1]	validation-mae:11687.97448
[2]	validation-mae:11061.97848
[3]	validation-mae:10524.82980
[4]	validation-mae:10050.49720
[5]	validation-mae:9622.80886
[6]	validation-mae:9275.28355
[7]	validation-mae:8971.97101
[8]	validation-mae:8702.86971
[9]	validation-mae:8437.44487

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12412.33756
[1]	validation-mae:11686.16236
[2]	validation-mae:11061.01499
[3]	validation-mae:10528.09256
[4]	validation-mae:10042.63909
[5]	validation-mae:9611.36481
[6]	validation-mae:9263.85868
[7]	validation-mae:8953.54133
[8]	validation-mae:8684.65684
[9]	validation-mae:8432.78870

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12426.17445
[1]	validation-mae:11713.40685
[2]	validation-mae:11087.89783
[3]	validation-mae:10552.52087
[4]	validation-mae:10074.48439
[5]	validation-mae:9648.82819
[6]	validation-mae:9292.06081
[7]	validation-mae:8987.38356
[8]	validation-mae:8717.70767
[9]	validation-mae:8470.07507

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12419.31846
[1]	validation-mae:11693.20281
[2]	validation-mae:11052.13993
[3]	validation-mae:10508.71598
[4]	validation-mae:10035.67985
[5]	validation-mae:9613.04438
[6]	validation-mae:9262.63220
[7]	validation-mae:8944.12510
[8]	validation-mae:8664.96661
[9]	validation-mae:8420.45147

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12456.61224
[0]	validation-mae:12458.40147
[0]	validation-mae:12417.61783
[1]	validation-mae:11695.63457
[2]	validation-mae:11050.86596
[3]	validation-mae:10507.05290
[4]	validation-mae:10028.57375
[5]	validation-mae:9609.65966
[6]	validation-mae:9257.88253
[7]	validation-mae:8941.41231
[8]	validation-mae:8666.51842
[9]	validation-mae:8419.38960

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12417.00443
[1]	validation-mae:11694.54722
[2]	validation-mae:11049.49709
[3]	validation-mae:10505.42097
[4]	validation-mae:10030.01749
[5]	validation-mae:9611.04855
[6]	validation-mae:9258.43871
[7]	validation-mae:8941.12536
[8]	validation-mae:8661.78297
[9]	validation-mae:8418.49164

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12413.90297
[1]	validation-mae:11690.68688
[2]	validation-mae:11051.04794
[3]	validation-mae:10513.42046
[4]	validation-mae:10033.21430
[5]	validation-mae:9616.02778
[6]	validation-mae:9239.77274
[7]	validation-mae:8944.06859
[8]	validation-mae:8668.78590
[9]	validation-mae:8412.57164

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12458.06007
[0]	validation-mae:12438.99469
[1]	validation-mae:11742.20696
[2]	validation-mae:11118.84451
[3]	validation-mae:10600.14604
[0]	validation-mae:12443.67413
[1]	validation-mae:11740.53235
[2]	validation-mae:11117.77611
[3]	validation-mae:10588.21361
[4]	validation-mae:10113.63846
[5]	validation-mae:9690.96981
[6]	validation-mae:9324.39470
[7]	validation-mae:9021.65112
[8]	validation-mae:8745.93523
[9]	validation-mae:8501.97155
[0]	validation-mae:12428.07677

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11720.07660
[2]	validation-mae:11098.30088
[3]	validation-mae:10563.83298
[4]	validation-mae:10084.34127
[5]	validation-mae:9660.84183
[6]	validation-mae:9307.66230
[7]	validation-mae:9007.02345
[8]	validation-mae:8735.75062
[9]	validation-mae:8486.99605
[0]	validation-mae:12453.99493

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12474.04337
[0]	validation-mae:12412.54743
[1]	validation-mae:11692.92619
[2]	validation-mae:11065.25560
[3]	validation-mae:10525.03968
[4]	validation-mae:10051.39058
[5]	validation-mae:9626.15049
[6]	validation-mae:9265.53466
[7]	validation-mae:8959.98118
[8]	validation-mae:8679.76152
[9]	validation-mae:8431.16139

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12413.70190
[1]	validation-mae:11688.48992
[2]	validation-mae:11053.08673
[3]	validation-mae:10518.76437
[4]	validation-mae:10037.44694
[5]	validation-mae:9612.97218
[6]	validation-mae:9264.93082
[7]	validation-mae:8954.79019
[8]	validation-mae:8692.06060
[9]	validation-mae:8438.40975
[0]	validation-mae:12414.30178
[1]	validation-mae:11695.62982
[2]	validation-mae:11064.31395

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[3]	validation-mae:10526.85086
[4]	validation-mae:10046.94320
[5]	validation-mae:9623.84806
[6]	validation-mae:9253.11838
[7]	validation-mae:8937.91497
[8]	validation-mae:8667.88883
[9]	validation-mae:8421.62428

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12437.07662
[1]	validation-mae:11735.32470
[2]	validation-mae:11115.06596
[3]	validation-mae:10587.20117
[4]	validation-mae:10111.69702
[5]	validation-mae:9693.85282
[6]	validation-mae:9326.69621
[7]	validation-mae:9024.80610
[8]	validation-mae:8749.61451
[9]	validation-mae:8486.83740
[0]	validation-mae:12456.20710

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12475.67728
[0]	validation-mae:12442.60819
[1]	validation-mae:11745.02787
[0]	validation-mae:12412.36022
[1]	validation-mae:11694.24346
[2]	validation-mae:11066.93590
[3]	validation-mae:10526.97137
[4]	validation-mae:10053.42275
[5]	validation-mae:9628.25259
[6]	validation-mae:9267.63584
[7]	validation-mae:8962.06715
[8]	validation-mae:8681.77134
[9]	validation-mae:8433.12858

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12418.51170
[1]	validation-mae:11701.94366
[2]	validation-mae:11082.34814
[3]	validation-mae:10549.30876
[4]	validation-mae:10072.68609
[5]	validation-mae:9646.82736
[6]	validation-mae:9282.97630
[7]	validation-mae:8974.86152
[8]	validation-mae:8686.73738
[9]	validation-mae:8440.37764
[0]	validation-mae:12435.30019

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[1]	validation-mae:11724.65816
[2]	validation-mae:11114.46152
[3]	validation-mae:10588.43436
[4]	validation-mae:10107.93740
[5]	validation-mae:9685.82335
[6]	validation-mae:9310.18092
[7]	validation-mae:9013.06478
[8]	validation-mae:8727.33448
[9]	validation-mae:8479.90757

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12417.88912
[1]	validation-mae:11699.83238
[2]	validation-mae:11067.24994
[3]	validation-mae:10525.07547
[4]	validation-mae:10039.25912
[5]	validation-mae:9621.57006
[6]	validation-mae:9248.84020
[7]	validation-mae:8926.14748
[8]	validation-mae:8663.89704
[9]	validation-mae:8409.45391

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12412.01578
[1]	validation-mae:11693.65400
[2]	validation-mae:11066.17655
[3]	validation-mae:10526.07467
[4]	validation-mae:10052.43719
[5]	validation-mae:9627.22853
[6]	validation-mae:9266.61598
[7]	validation-mae:8961.05926
[8]	validation-mae:8680.80876
[9]	validation-mae:8432.18746

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12412.01866
[1]	validation-mae:11688.21892
[2]	validation-mae:11059.15733
[3]	validation-mae:10517.21174
[4]	validation-mae:10029.30468
[5]	validation-mae:9614.86617
[6]	validation-mae:9255.62000
[7]	validation-mae:8955.11354
[8]	validation-mae:8673.19861
[9]	validation-mae:8424.76933
[0]	validation-mae:12473.90235

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.98819
[1]	validation-mae:11693.57758
[2]	validation-mae:11055.84765
[3]	validation-mae:10519.42221
[4]	validation-mae:10042.90851
[5]	validation-mae:9615.50254
[6]	validation-mae:9242.32536
[7]	validation-mae:8945.21702
[8]	validation-mae:8677.33828
[9]	validation-mae:8417.96233

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12443.98864
[0]	validation-mae:12411.74058
[1]	validation-mae:11692.46221
[2]	validation-mae:11061.67921
[3]	validation-mae:10518.98184
[4]	validation-mae:10038.51416
[5]	validation-mae:9617.12304
[6]	validation-mae:9258.96642
[7]	validation-mae:8958.98030
[8]	validation-mae:8681.21116
[9]	validation-mae:8433.66671

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12415.72415
[1]	validation-mae:11696.12505
[2]	validation-mae:11069.72611
[3]	validation-mae:10532.72190
[4]	validation-mae:10059.44326
[5]	validation-mae:9632.14241
[6]	validation-mae:9268.77542
[7]	validation-mae:8964.92012
[8]	validation-mae:8670.35784
[9]	validation-mae:8421.28233

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12424.63627
[1]	validation-mae:11713.06793
[2]	validation-mae:11090.28738
[3]	validation-mae:10553.15135
[4]	validation-mae:10067.84257
[5]	validation-mae:9655.25485
[6]	validation-mae:9302.32220
[7]	validation-mae:9002.59638
[8]	validation-mae:8719.53010
[9]	validation-mae:8459.72498

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12429.02628
[1]	validation-mae:11716.29039
[2]	validation-mae:11096.13400
[3]	validation-mae:10580.86176
[4]	validation-mae:10127.51880
[0]	validation-mae:12429.89279
[1]	validation-mae:11718.31356
[2]	validation-mae:11091.70077
[3]	validation-mae:10557.82984
[4]	validation-mae:10078.91474
[5]	validation-mae:9651.09124
[6]	validation-mae:9293.05194
[7]	validation-mae:8991.44997
[8]	validation-mae:8713.04885
[9]	validation-mae:8461.54728

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12413.86767
[1]	validation-mae:11690.74173
[2]	validation-mae:11052.12196
[3]	validation-mae:10515.44420
[4]	validation-mae:10035.12510
[5]	validation-mae:9618.12429
[6]	validation-mae:9241.24382
[7]	validation-mae:8943.49571
[8]	validation-mae:8667.55756
[9]	validation-mae:8409.58115

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12428.66152
[1]	validation-mae:11723.00197
[2]	validation-mae:11093.05352
[3]	validation-mae:10572.66802
[4]	validation-mae:10096.44498
[5]	validation-mae:9675.19977
[6]	validation-mae:9300.78190
[7]	validation-mae:8973.44659
[8]	validation-mae:8718.93205
[9]	validation-mae:8454.39313

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.09686
[1]	validation-mae:11691.55285
[2]	validation-mae:11048.81828
[3]	validation-mae:10504.10922
[4]	validation-mae:10026.56431
[5]	validation-mae:9602.53754
[6]	validation-mae:9243.77002
[7]	validation-mae:8930.03751
[8]	validation-mae:8656.70718
[9]	validation-mae:8406.30434

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12444.44241
[0]	validation-mae:12473.14166
[0]	validation-mae:12406.68522
[1]	validation-mae:11693.81520
[2]	validation-mae:11054.54272
[3]	validation-mae:10518.04628
[4]	validation-mae:10043.46198
[5]	validation-mae:9626.67741
[6]	validation-mae:9254.90080
[7]	validation-mae:8957.60307
[8]	validation-mae:8687.20883
[9]	validation-mae:8441.37653

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12446.49427
[0]	validation-mae:12501.36324
[0]	validation-mae:12431.98142
[1]	validation-mae:11721.25000
[2]	validation-mae:11087.69147
[3]	validation-mae:10552.63395
[4]	validation-mae:10077.56210
[5]	validation-mae:9651.63334
[6]	validation-mae:9278.01764
[7]	validation-mae:8972.02003
[8]	validation-mae:8700.14671
[9]	validation-mae:8450.41628

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12416.51753
[1]	validation-mae:11696.60254
[2]	validation-mae:11065.03408
[3]	validation-mae:10522.67931
[4]	validation-mae:10035.49726
[5]	validation-mae:9621.21655
[6]	validation-mae:9266.60974
[7]	validation-mae:8963.27441
[8]	validation-mae:8683.24094
[9]	validation-mae:8438.62130

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12415.63079
[1]	validation-mae:11694.70250
[2]	validation-mae:11051.13675
[3]	validation-mae:10512.44844
[4]	validation-mae:10035.90301
[5]	validation-mae:9608.31655
[6]	validation-mae:9237.07332
[7]	validation-mae:8935.68825
[8]	validation-mae:8665.90671
[9]	validation-mae:8417.68168

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12530.74466
[0]	validation-mae:12441.12159
[0]	validation-mae:12457.18897
[0]	validation-mae:12433.25162
[1]	validation-mae:11725.37150
[2]	validation-mae:11097.73088
[3]	validation-mae:10567.43680
[4]	validation-mae:10082.94025
[5]	validation-mae:9667.52936
[6]	validation-mae:9295.37219
[7]	validation-mae:8974.35776
[8]	validation-mae:8709.81622
[9]	validation-mae:8458.12776

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12429.70804
[1]	validation-mae:11718.03371
[2]	validation-mae:11091.32625
[3]	validation-mae:10555.21156
[4]	validation-mae:10074.77415
[5]	validation-mae:9651.96746
[6]	validation-mae:9294.33166
[7]	validation-mae:9002.33226
[8]	validation-mae:8716.77228
[9]	validation-mae:8461.58841
[0]	validation-mae:12461.35997

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12432.69344
[1]	validation-mae:11723.43419
[0]	validation-mae:12411.49637
[1]	validation-mae:11691.50720
[2]	validation-mae:11061.57949
[3]	validation-mae:10519.65412
[4]	validation-mae:10038.21039
[5]	validation-mae:9609.65784
[6]	validation-mae:9255.50019
[7]	validation-mae:8957.40015
[8]	validation-mae:8683.18859
[9]	validation-mae:8435.47768

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12428.47339
[1]	validation-mae:11721.58213
[2]	validation-mae:11100.98903
[3]	validation-mae:10560.09008
[4]	validation-mae:10076.64969
[5]	validation-mae:9654.04844
[6]	validation-mae:9289.50972
[7]	validation-mae:8994.10257
[8]	validation-mae:8727.64736
[9]	validation-mae:8476.16571

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12416.39504
[1]	validation-mae:11693.50786
[2]	validation-mae:11048.15191
[3]	validation-mae:10503.84026
[4]	validation-mae:10028.27580
[5]	validation-mae:9609.24700
[6]	validation-mae:9256.63644
[7]	validation-mae:8939.34014
[8]	validation-mae:8660.08219
[9]	validation-mae:8416.85110

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12470.86290
[0]	validation-mae:12856.14235
[0]	validation-mae:12430.24043
[1]	validation-mae:11718.99164
[2]	validation-mae:11092.56605
[3]	validation-mae:10556.67560
[4]	validation-mae:10076.40476
[5]	validation-mae:9653.67053
[6]	validation-mae:9298.64199
[7]	validation-mae:9006.24205
[8]	validation-mae:8728.27044
[9]	validation-mae:8471.56338

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12456.21102
[0]	validation-mae:12430.10985
[1]	validation-mae:11720.46684
[2]	validation-mae:11092.02154
[3]	validation-mae:10558.25776
[4]	validation-mae:10081.13359
[5]	validation-mae:9656.00920
[6]	validation-mae:9296.28648
[7]	validation-mae:9001.07975
[8]	validation-mae:8730.59859
[9]	validation-mae:8473.70353

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12455.55005
[0]	validation-mae:12824.86113
[0]	validation-mae:12444.18568
[0]	validation-mae:12458.87315
[0]	validation-mae:12431.09405
[1]	validation-mae:11715.60015
[2]	validation-mae:11101.91669
[0]	validation-mae:12413.84781
[1]	validation-mae:11693.59459
[2]	validation-mae:11056.16062
[3]	validation-mae:10511.20090
[4]	validation-mae:10027.47396
[5]	validation-mae:9609.24959
[6]	validation-mae:9262.12928
[7]	validation-mae:8944.65869
[8]	validation-mae:8670.72503
[9]	validation-mae:8407.88163

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12446.63414
[0]	validation-mae:12716.75741
[0]	validation-mae:12398.20205
[1]	validation-mae:11643.43263
[2]	validation-mae:10999.70784
[3]	validation-mae:10431.48461
[4]	validation-mae:9923.79597
[5]	validation-mae:9493.83248
[6]	validation-mae:9142.70297
[7]	validation-mae:8813.56119
[8]	validation-mae:8525.58638
[9]	validation-mae:8295.53064

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12422.51955
[1]	validation-mae:11706.62468
[2]	validation-mae:11077.15491
[3]	validation-mae:10540.24297
[4]	validation-mae:10075.89840
[5]	validation-mae:9668.77967
[6]	validation-mae:9313.03452
[7]	validation-mae:8988.51948
[8]	validation-mae:8719.44608
[9]	validation-mae:8488.51340

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12755.41722
[0]	validation-mae:12562.12541
[0]	validation-mae:12412.03914
[1]	validation-mae:11695.74571
[2]	validation-mae:11059.39512
[3]	validation-mae:10526.86112
[4]	validation-mae:10044.18471
[5]	validation-mae:9621.37664
[6]	validation-mae:9243.93473
[7]	validation-mae:8945.97299
[8]	validation-mae:8672.49635
[9]	validation-mae:8421.61734

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12431.93498
[1]	validation-mae:11723.72803
[0]	validation-mae:12420.21289
[1]	validation-mae:11713.07885
[2]	validation-mae:11083.42664
[3]	validation-mae:10552.42877
[4]	validation-mae:10075.84664
[5]	validation-mae:9655.71588
[6]	validation-mae:9283.21420
[7]	validation-mae:8982.54290
[8]	validation-mae:8714.15795
[9]	validation-mae:8473.00785

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12607.53924
[0]	validation-mae:12410.99895
[1]	validation-mae:11695.12438
[2]	validation-mae:11059.14521
[3]	validation-mae:10515.36180
[4]	validation-mae:10038.73528
[5]	validation-mae:9606.77343
[6]	validation-mae:9252.65941
[7]	validation-mae:8957.00807
[8]	validation-mae:8693.13516
[9]	validation-mae:8436.73808

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12487.42380
[0]	validation-mae:12478.20655
[0]	validation-mae:12414.22458
[1]	validation-mae:11692.22221
[2]	validation-mae:11055.29047
[3]	validation-mae:10515.49078
[4]	validation-mae:10033.54164
[5]	validation-mae:9613.44028
[6]	validation-mae:9234.48074
[7]	validation-mae:8939.14728
[8]	validation-mae:8663.38148
[9]	validation-mae:8406.69754

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12429.99033
[1]	validation-mae:11719.45278
[2]	validation-mae:11090.54670
[3]	validation-mae:10557.37126
[4]	validation-mae:10079.04530
[5]	validation-mae:9653.21938
[6]	validation-mae:9273.27214
[7]	validation-mae:8980.94920
[8]	validation-mae:8705.56696
[9]	validation-mae:8457.99551

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12717.00995
[0]	validation-mae:12415.67947
[1]	validation-mae:11692.01702
[2]	validation-mae:11050.42445
[3]	validation-mae:10514.74991
[4]	validation-mae:10033.09717
[5]	validation-mae:9614.02033
[6]	validation-mae:9248.76613
[7]	validation-mae:8945.17662
[8]	validation-mae:8681.90497
[9]	validation-mae:8432.48805

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12430.83587
[0]	validation-mae:12432.91957
[0]	validation-mae:12470.28576
[0]	validation-mae:12451.50753
[0]	validation-mae:12427.15591
[1]	validation-mae:11713.26015
[2]	validation-mae:11080.91198
[3]	validation-mae:10550.17584
[4]	validation-mae:10079.79002
[5]	validation-mae:9656.18685
[6]	validation-mae:9284.73089
[7]	validation-mae:8991.10013
[8]	validation-mae:8721.87574
[9]	validation-mae:8477.22964

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12414.73531
[1]	validation-mae:11693.18610
[2]	validation-mae:11055.33109
[3]	validation-mae:10519.69139
[4]	validation-mae:10043.15158
[5]	validation-mae:9615.72993
[6]	validation-mae:9242.67354
[7]	validation-mae:8945.56446
[8]	validation-mae:8677.35734
[9]	validation-mae:8419.27876

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12441.95311
[0]	validation-mae:12470.30806
[0]	validation-mae:12678.46949
[0]	validation-mae:12413.06616
[1]	validation-mae:11694.44026
[2]	validation-mae:11062.22600
[3]	validation-mae:10523.06358
[4]	validation-mae:10044.11709
[5]	validation-mae:9622.03084
[6]	validation-mae:9251.61186
[7]	validation-mae:8936.24801
[8]	validation-mae:8670.29446
[9]	validation-mae:8415.52221

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12426.14392
[1]	validation-mae:11716.79695
[2]	validation-mae:11091.07206
[3]	validation-mae:10556.78877
[4]	validation-mae:10077.75061
[5]	validation-mae:9651.82348
[6]	validation-mae:9275.43562
[7]	validation-mae:8968.89881
[8]	validation-mae:8719.97415
[9]	validation-mae:8472.66976

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12415.19009
[1]	validation-mae:11695.27996
[2]	validation-mae:11068.52824
[3]	validation-mae:10530.28191
[4]	validation-mae:10053.68397
[5]	validation-mae:9628.71241
[6]	validation-mae:9259.62530
[7]	validation-mae:8957.81192
[8]	validation-mae:8676.06384
[9]	validation-mae:8424.54800

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12437.92157
[0]	validation-mae:12496.19577
[0]	validation-mae:12522.08688
[0]	validation-mae:12429.64478
[0]	validation-mae:12411.43864
[1]	validation-mae:11691.10786
[2]	validation-mae:11061.71419
[3]	validation-mae:10519.48118
[4]	validation-mae:10038.40517
[5]	validation-mae:9611.68567
[6]	validation-mae:9249.05679
[7]	validation-mae:8935.25325
[8]	validation-mae:8677.19741
[9]	validation-mae:8436.48046

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12447.84842
[0]	validation-mae:12540.13673
[0]	validation-mae:12411.85552
[1]	validation-mae:11694.43750
[2]	validation-mae:11057.89676
[3]	validation-mae:10521.90409
[4]	validation-mae:10042.47136
[5]	validation-mae:9617.44763
[6]	validation-mae:9243.76596
[7]	validation-mae:8947.76469
[8]	validation-mae:8678.13283
[9]	validation-mae:8427.58251

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12589.62605
[0]	validation-mae:12424.51215
[1]	validation-mae:11713.53597
[2]	validation-mae:11090.50622
[3]	validation-mae:10556.20404
[4]	validation-mae:10077.43548
[5]	validation-mae:9651.63984
[6]	validation-mae:9298.98633
[7]	validation-mae:8999.43261
[8]	validation-mae:8724.55874
[9]	validation-mae:8470.81224

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12487.97481
[0]	validation-mae:13023.22773
[0]	validation-mae:12414.23606
[1]	validation-mae:11693.93395
[2]	validation-mae:11075.16583
[3]	validation-mae:10535.12078
[4]	validation-mae:10049.02527
[5]	validation-mae:9621.97179
[6]	validation-mae:9272.65868
[7]	validation-mae:8969.55970
[8]	validation-mae:8700.63230
[9]	validation-mae:8453.11103

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12432.38167
[0]	validation-mae:12468.56768
[0]	validation-mae:12417.94628
[1]	validation-mae:11698.02915
[2]	validation-mae:11076.90890
[3]	validation-mae:10538.31587
[4]	validation-mae:10060.99455
[5]	validation-mae:9637.02860
[6]	validation-mae:9269.88991
[7]	validation-mae:8963.45790
[8]	validation-mae:8677.97305
[9]	validation-mae:8428.26097

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12469.90879
[0]	validation-mae:12412.90701
[1]	validation-mae:11694.14896
[2]	validation-mae:11061.85930
[3]	validation-mae:10522.61456
[4]	validation-mae:10043.62615
[5]	validation-mae:9621.50872
[6]	validation-mae:9250.94556
[7]	validation-mae:8935.58977
[8]	validation-mae:8669.65406
[9]	validation-mae:8415.05269

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12433.58051
[0]	validation-mae:12455.92576
[0]	validation-mae:12420.67344
[1]	validation-mae:11711.87162
[2]	validation-mae:11078.94122
[3]	validation-mae:10547.16328
[4]	validation-mae:10072.53623
[5]	validation-mae:9656.98926
[6]	validation-mae:9295.57518
[7]	validation-mae:8981.72185
[8]	validation-mae:8726.65733
[9]	validation-mae:8466.68347

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12898.02111
[0]	validation-mae:12537.02666
[0]	validation-mae:12415.25178
[1]	validation-mae:11699.14928
[2]	validation-mae:11060.74146
[3]	validation-mae:10533.09179
[4]	validation-mae:10057.77570
[5]	validation-mae:9636.36211
[6]	validation-mae:9263.81846
[7]	validation-mae:8957.81857
[8]	validation-mae:8704.29882
[9]	validation-mae:8450.40239

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12425.66678
[1]	validation-mae:11718.22399
[2]	validation-mae:11085.13984
[0]	validation-mae:12456.41787
[0]	validation-mae:12482.27823
[0]	validation-mae:12489.20452
[0]	validation-mae:12412.14686
[1]	validation-mae:11691.52814
[2]	validation-mae:11064.51415
[3]	validation-mae:10527.16979
[4]	validation-mae:10052.18552
[5]	validation-mae:9622.39077
[6]	validation-mae:9262.43833
[7]	validation-mae:8956.69845
[8]	validation-mae:8679.50962
[9]	validation-mae:8431.90038

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12443.67153
[0]	validation-mae:12472.51069
[0]	validation-mae:12496.16523
[0]	validation-mae:12428.83190
[0]	validation-mae:12404.75675
[1]	validation-mae:11687.09801
[2]	validation-mae:11049.35471
[3]	validation-mae:10517.37214
[4]	validation-mae:10028.42562
[5]	validation-mae:9596.42788
[6]	validation-mae:9230.96934
[7]	validation-mae:8945.10264
[8]	validation-mae:8670.51494
[9]	validation-mae:8419.85005

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12432.62138
[0]	validation-mae:12421.48870
[1]	validation-mae:11712.92376
[2]	validation-mae:11081.69179
[3]	validation-mae:10546.39307
[4]	validation-mae:10074.04337
[5]	validation-mae:9658.35040
[6]	validation-mae:9294.97373
[7]	validation-mae:8977.03736
[8]	validation-mae:8721.08959
[9]	validation-mae:8465.80379

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12798.47139
[0]	validation-mae:12411.67752
[1]	validation-mae:11695.16741
[2]	validation-mae:11056.64146
[3]	validation-mae:10517.04849
[4]	validation-mae:10033.48654
[5]	validation-mae:9604.79271
[6]	validation-mae:9228.97207
[7]	validation-mae:8940.23833
[8]	validation-mae:8677.27155
[9]	validation-mae:8430.60267

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12426.69675
[1]	validation-mae:11719.81838
[0]	validation-mae:12479.30431
[0]	validation-mae:12429.63093
[1]	validation-mae:11727.98870
[0]	validation-mae:12515.99109
[0]	validation-mae:12443.55459
[0]	validation-mae:12495.73179
[0]	validation-mae:12413.57459
[1]	validation-mae:11693.11906
[2]	validation-mae:11055.55999
[3]	validation-mae:10510.48420
[4]	validation-mae:10029.98205
[5]	validation-mae:9611.72848
[6]	validation-mae:9266.48825
[7]	validation-mae:8954.95914
[8]	validation-mae:8684.97986
[9]	validation-mae:8447.63738

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12433.66880
[0]	validation-mae:12512.29944
[0]	validation-mae:12866.29499
[0]	validation-mae:12427.83227
[1]	validation-mae:11718.51565
[0]	validation-mae:12492.79706
[0]	validation-mae:12414.07611
[1]	validation-mae:11685.68027
[2]	validation-mae:11053.70445
[3]	validation-mae:10510.29961
[4]	validation-mae:10036.30767
[5]	validation-mae:9611.86801
[6]	validation-mae:9265.02400
[7]	validation-mae:8959.59644
[8]	validation-mae:8688.48166
[9]	validation-mae:8423.26096

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:13069.94373
[0]	validation-mae:12416.57897
[1]	validation-mae:11695.69652
[2]	validation-mae:11057.20997
[3]	validation-mae:10516.20910
[4]	validation-mae:10035.04543
[5]	validation-mae:9614.56922
[6]	validation-mae:9235.71121
[7]	validation-mae:8932.14154
[8]	validation-mae:8668.78577
[9]	validation-mae:8411.37664

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12432.47479
[0]	validation-mae:12428.62235
[0]	validation-mae:12475.93379
[0]	validation-mae:12426.79092
[1]	validation-mae:11717.85773
[0]	validation-mae:12417.82077
[1]	validation-mae:11700.77147
[2]	validation-mae:11080.84036
[3]	validation-mae:10547.52228
[4]	validation-mae:10070.75648
[5]	validation-mae:9644.81672
[6]	validation-mae:9280.93804
[7]	validation-mae:8972.82806
[8]	validation-mae:8684.80947
[9]	validation-mae:8438.47417

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12412.68937
[1]	validation-mae:11693.70530
[2]	validation-mae:11064.12288
[3]	validation-mae:10522.43688
[4]	validation-mae:10045.65371
[5]	validation-mae:9626.61892
[6]	validation-mae:9255.94336
[7]	validation-mae:8936.97401
[8]	validation-mae:8671.43387
[9]	validation-mae:8433.09325

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12494.82029
[0]	validation-mae:12557.19900
[0]	validation-mae:12455.76140
[0]	validation-mae:12978.84043
[0]	validation-mae:12421.78904
[0]	validation-mae:12414.28702
[1]	validation-mae:11693.46705
[2]	validation-mae:11075.30705
[3]	validation-mae:10536.16423
[4]	validation-mae:10057.44240
[5]	validation-mae:9624.88658
[6]	validation-mae:9274.58733
[7]	validation-mae:8961.09249
[8]	validation-mae:8677.70844
[9]	validation-mae:8415.69450

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12450.72818
[0]	validation-mae:12414.21351
[1]	validation-mae:11693.35880
[2]	validation-mae:11074.08417
[3]	validation-mae:10535.21389
[4]	validation-mae:10056.50154
[5]	validation-mae:9624.06375
[6]	validation-mae:9273.58390
[7]	validation-mae:8958.01123
[8]	validation-mae:8671.37807
[9]	validation-mae:8409.68574

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12431.30909
[0]	validation-mae:12414.73890
[1]	validation-mae:11696.07945
[2]	validation-mae:11068.24887
[3]	validation-mae:10529.40197
[4]	validation-mae:10044.31435
[5]	validation-mae:9619.80058
[6]	validation-mae:9265.57280
[7]	validation-mae:8956.97929
[8]	validation-mae:8678.56557
[9]	validation-mae:8425.50042

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12431.01714
[0]	validation-mae:12418.20367
[1]	validation-mae:11698.42038
[2]	validation-mae:11078.46294
[3]	validation-mae:10540.01221
[4]	validation-mae:10064.77458
[5]	validation-mae:9640.94690
[6]	validation-mae:9273.26679
[7]	validation-mae:8966.81197
[8]	validation-mae:8679.52290
[9]	validation-mae:8427.06448

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:13164.92796
[0]	validation-mae:12412.36791
[1]	validation-mae:11694.68090
[2]	validation-mae:11058.52243
[3]	validation-mae:10527.45936
[4]	validation-mae:10050.59031
[5]	validation-mae:9630.25039
[6]	validation-mae:9260.11762
[7]	validation-mae:8954.35205
[8]	validation-mae:8704.84413
[9]	validation-mae:8435.64352
[0]	validation-mae:12481.60642

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12415.97080
[1]	validation-mae:11697.70109
[2]	validation-mae:11065.86142
[3]	validation-mae:10526.29638
[4]	validation-mae:10052.61939
[5]	validation-mae:9624.14575
[6]	validation-mae:9255.95865
[7]	validation-mae:8952.04637
[8]	validation-mae:8680.58969
[9]	validation-mae:8427.66542

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12442.43911
[0]	validation-mae:12418.13620
[1]	validation-mae:11707.92306
[2]	validation-mae:11087.82902
[3]	validation-mae:10535.53706
[4]	validation-mae:10055.33628
[5]	validation-mae:9638.54043
[6]	validation-mae:9274.49905
[7]	validation-mae:8972.11348
[8]	validation-mae:8715.72868
[9]	validation-mae:8460.37576

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12469.50696
[0]	validation-mae:12452.61669
[0]	validation-mae:12631.43229
[0]	validation-mae:12431.13834
[0]	validation-mae:12570.72757
[0]	validation-mae:12456.64736
[0]	validation-mae:12416.75099
[1]	validation-mae:11697.81812
[2]	validation-mae:11063.65898
[3]	validation-mae:10520.89920
[4]	validation-mae:10039.19739
[5]	validation-mae:9611.65939
[6]	validation-mae:9241.72806
[7]	validation-mae:8925.79014
[8]	validation-mae:8660.56049
[9]	validation-mae:8404.51284

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12416.59326
[1]	validation-mae:11693.83921
[2]	validation-mae:11048.58681
[3]	validation-mae:10504.34771
[4]	validation-mae:10028.82531
[5]	validation-mae:9609.81742
[6]	validation-mae:9257.20509
[7]	validation-mae:8939.90927
[8]	validation-mae:8660.62752
[9]	validation-mae:8417.38073

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12459.28930
[0]	validation-mae:12422.99324
[1]	validation-mae:11716.22583
[0]	validation-mae:12571.85116
[0]	validation-mae:12414.67406
[1]	validation-mae:11695.38782
[2]	validation-mae:11066.26365
[3]	validation-mae:10526.95263
[4]	validation-mae:10046.56308
[5]	validation-mae:9621.06022
[6]	validation-mae:9269.88424
[7]	validation-mae:8964.62947
[8]	validation-mae:8669.07401
[9]	validation-mae:8406.49498

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12526.92490
[0]	validation-mae:12419.78496
[1]	validation-mae:11697.37643
[2]	validation-mae:11070.60452
[3]	validation-mae:10539.36350
[4]	validation-mae:10056.19155
[5]	validation-mae:9633.80634
[6]	validation-mae:9274.56698
[7]	validation-mae:8984.11103
[8]	validation-mae:8716.30958
[9]	validation-mae:8457.67724

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12461.38675
[0]	validation-mae:12522.71216
[0]	validation-mae:12778.12883
[0]	validation-mae:12451.64923
[0]	validation-mae:12432.27356
[0]	validation-mae:12568.95863
[0]	validation-mae:12412.37520
[1]	validation-mae:11693.49774
[2]	validation-mae:11063.40915
[3]	validation-mae:10523.54114
[4]	validation-mae:10043.17056
[5]	validation-mae:9614.98303
[6]	validation-mae:9253.56383
[7]	validation-mae:8953.52443
[8]	validation-mae:8671.80077
[9]	validation-mae:8416.58505

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12418.25260
[1]	validation-mae:11704.14692
[2]	validation-mae:11082.61743
[3]	validation-mae:10546.17632
[4]	validation-mae:10060.35667
[5]	validation-mae:9636.61871
[6]	validation-mae:9278.60754
[7]	validation-mae:8957.92528
[8]	validation-mae:8693.95577
[9]	validation-mae:8434.68060

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12528.89504
[0]	validation-mae:12454.76560
[0]	validation-mae:12426.99006
[1]	validation-mae:11717.68770
[0]	validation-mae:12489.40734
[0]	validation-mae:12672.84807
[0]	validation-mae:12408.43266
[1]	validation-mae:11688.55054
[2]	validation-mae:11048.82929
[3]	validation-mae:10508.47722
[4]	validation-mae:10029.95706
[5]	validation-mae:9609.87167
[6]	validation-mae:9255.83807
[7]	validation-mae:8945.61421
[8]	validation-mae:8696.92774
[9]	validation-mae:8443.10687

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12418.08371
[1]	validation-mae:11701.22407
[2]	validation-mae:11081.42192
[3]	validation-mae:10548.21778
[4]	validation-mae:10071.51538
[5]	validation-mae:9645.60800
[6]	validation-mae:9281.73458
[7]	validation-mae:8973.61792
[8]	validation-mae:8685.55853
[9]	validation-mae:8439.21304

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12458.80921
[0]	validation-mae:12469.13287
[0]	validation-mae:12524.26282
[0]	validation-mae:12417.29006
[1]	validation-mae:11696.95011
[2]	validation-mae:11058.83576
[3]	validation-mae:10518.09497
[4]	validation-mae:10037.13960
[5]	validation-mae:9616.75223
[6]	validation-mae:9238.03305
[7]	validation-mae:8934.39893
[8]	validation-mae:8670.61038
[9]	validation-mae:8413.05387

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12412.70990
[1]	validation-mae:11693.79352
[2]	validation-mae:11061.40948
[3]	validation-mae:10522.06828
[4]	validation-mae:10043.03038
[5]	validation-mae:9620.87663
[6]	validation-mae:9250.31876
[7]	validation-mae:8934.96589
[8]	validation-mae:8669.04988
[9]	validation-mae:8415.16828

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12488.22805
[0]	validation-mae:12454.90902
[0]	validation-mae:12440.03673
[0]	validation-mae:12458.29729
[0]	validation-mae:12441.17316
[0]	validation-mae:12469.82242
[0]	validation-mae:12411.73492
[1]	validation-mae:11687.73314
[2]	validation-mae:11058.53102
[3]	validation-mae:10516.47367
[4]	validation-mae:10028.49833
[5]	validation-mae:9614.02493
[6]	validation-mae:9254.78551
[7]	validation-mae:8954.30155
[8]	validation-mae:8672.40787
[9]	validation-mae:8427.05117

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12470.98294
[0]	validation-mae:12442.19634
[0]	validation-mae:12406.36606
[1]	validation-mae:11689.41185
[2]	validation-mae:11052.65576
[3]	validation-mae:10516.86640
[4]	validation-mae:10036.69014
[5]	validation-mae:9619.82473
[6]	validation-mae:9241.20165
[7]	validation-mae:8914.75635
[8]	validation-mae:8649.27836
[9]	validation-mae:8408.96677

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12487.92359
[0]	validation-mae:12459.59237
[0]	validation-mae:12480.99590
[0]	validation-mae:13143.83005
[0]	validation-mae:12414.92222
[1]	validation-mae:11693.44788
[2]	validation-mae:11055.68489
[3]	validation-mae:10519.22217
[4]	validation-mae:10042.68262
[5]	validation-mae:9615.26538
[6]	validation-mae:9242.09493
[7]	validation-mae:8944.99837
[8]	validation-mae:8677.13231
[9]	validation-mae:8417.76840

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12444.48561
[0]	validation-mae:12481.57165
[0]	validation-mae:12429.75679
[0]	validation-mae:12413.70236
[1]	validation-mae:11694.61155
[2]	validation-mae:11063.00061
[3]	validation-mae:10525.31800
[4]	validation-mae:10045.28687
[5]	validation-mae:9622.11193
[6]	validation-mae:9251.37126
[7]	validation-mae:8936.16249
[8]	validation-mae:8666.19312
[9]	validation-mae:8420.01880

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12417.17980
[1]	validation-mae:11696.33068
[2]	validation-mae:11053.62808
[3]	validation-mae:10525.52546
[4]	validation-mae:10050.69808
[5]	validation-mae:9639.26160
[6]	validation-mae:9281.88009
[7]	validation-mae:8963.54254
[8]	validation-mae:8695.59313
[9]	validation-mae:8455.78582

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12410.27873
[1]	validation-mae:11693.45440
[2]	validation-mae:11062.05843
[3]	validation-mae:10531.38975
[4]	validation-mae:10055.81876
[5]	validation-mae:9633.97016
[6]	validation-mae:9259.51044
[7]	validation-mae:8953.05571
[8]	validation-mae:8698.08278
[9]	validation-mae:8452.24845

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12450.18122
[0]	validation-mae:12413.57786
[1]	validation-mae:11690.44032
[2]	validation-mae:11053.88381
[3]	validation-mae:10518.55844
[4]	validation-mae:10036.69573
[5]	validation-mae:9610.45250
[6]	validation-mae:9253.31121
[7]	validation-mae:8950.66127
[8]	validation-mae:8675.92354
[9]	validation-mae:8432.66027

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12438.06065
[0]	validation-mae:12472.60739
[0]	validation-mae:12444.81291
[0]	validation-mae:12417.52778
[1]	validation-mae:11701.28938
[2]	validation-mae:11079.85869
[3]	validation-mae:10545.26277
[4]	validation-mae:10069.13465
[5]	validation-mae:9643.36869
[6]	validation-mae:9277.70156
[7]	validation-mae:8960.58058
[8]	validation-mae:8699.48248
[9]	validation-mae:8450.26949

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12688.16188
[0]	validation-mae:12455.11485
[0]	validation-mae:12416.71407
[1]	validation-mae:11697.81861
[2]	validation-mae:11065.42704
[3]	validation-mae:10523.44560
[4]	validation-mae:10035.87095
[5]	validation-mae:9623.00163
[6]	validation-mae:9267.53809
[7]	validation-mae:8964.20909
[8]	validation-mae:8682.43375
[9]	validation-mae:8429.22833

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12519.01685
[0]	validation-mae:12404.93600
[1]	validation-mae:11687.62921
[2]	validation-mae:11052.85526
[3]	validation-mae:10513.89679
[4]	validation-mae:10035.92572
[5]	validation-mae:9609.47348
[6]	validation-mae:9244.61637
[7]	validation-mae:8934.90240
[8]	validation-mae:8682.57013
[9]	validation-mae:8427.20922

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12413.36421
[1]	validation-mae:11688.89200
[2]	validation-mae:11049.81527
[3]	validation-mae:10512.69880
[4]	validation-mae:10031.79812
[5]	validation-mae:9608.33404
[6]	validation-mae:9241.94272
[7]	validation-mae:8940.67083
[8]	validation-mae:8665.89693
[9]	validation-mae:8416.43970

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12445.58399
[0]	validation-mae:12461.55141
[0]	validation-mae:12818.86255
[0]	validation-mae:12461.37998
[0]	validation-mae:12484.22238
[0]	validation-mae:12416.51309
[1]	validation-mae:11705.12547
[2]	validation-mae:11099.34069
[0]	validation-mae:12425.92168
[0]	validation-mae:12457.30765
[0]	validation-mae:12417.34085
[1]	validation-mae:11698.03346
[2]	validation-mae:11067.23713
[3]	validation-mae:10525.31905
[4]	validation-mae:10038.29848
[5]	validation-mae:9617.56122
[6]	validation-mae:9247.90746
[7]	validation-mae:8950.23611
[8]	validation-mae:8672.37515
[9]	validation-mae:8430.78919

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12486.78108
[0]	validation-mae:12404.88909
[1]	validation-mae:11687.31502
[2]	validation-mae:11052.92568
[3]	validation-mae:10513.25267
[4]	validation-mae:10037.10363
[5]	validation-mae:9613.22322
[6]	validation-mae:9245.92468
[7]	validation-mae:8945.10766
[8]	validation-mae:8688.40359
[9]	validation-mae:8435.17210

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12432.38500
[0]	validation-mae:12465.54175
[0]	validation-mae:12416.53795
[1]	validation-mae:11696.10187
[2]	validation-mae:11067.48170
[3]	validation-mae:10529.79262
[4]	validation-mae:10054.31449
[5]	validation-mae:9629.23401
[6]	validation-mae:9261.02776
[7]	validation-mae:8959.54179
[8]	validation-mae:8663.95842
[9]	validation-mae:8405.98454

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12483.74618
[0]	validation-mae:12479.14963
[0]	validation-mae:12975.77038
[0]	validation-mae:12407.85103
[1]	validation-mae:11689.04398
[2]	validation-mae:11052.00961
[3]	validation-mae:10510.98241
[4]	validation-mae:10031.95921
[5]	validation-mae:9613.01500
[6]	validation-mae:9249.42725
[7]	validation-mae:8934.88557
[8]	validation-mae:8677.59732
[9]	validation-mae:8436.24323

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12453.04758
[0]	validation-mae:12661.68257
[0]	validation-mae:12430.22350
[0]	validation-mae:13209.33545
[0]	validation-mae:12602.28051
[0]	validation-mae:12484.65500
[0]	validation-mae:12828.64121
[0]	validation-mae:12434.27123
[0]	validation-mae:12417.25977
[1]	validation-mae:11684.14463
[2]	validation-mae:11053.66991
[3]	validation-mae:10503.62504
[4]	validation-mae:10045.88447
[5]	validation-mae:9654.53180
[0]	validation-mae:12429.11346
[0]	validation-mae:12508.05888
[0]	validation-mae:12418.33120
[1]	validation-mae:11690.51254
[2]	validation-mae:11062.48106
[3]	validation-mae:10531.82873
[4]	validation-mae:10051.53228
[5]	validation-mae:9627.18596
[6]	validation-mae:9270.77144
[7]	validation-mae:8977.40788
[8]	validation-mae:8702.24475
[9]	validation-mae:8451.07887

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12664.46250
[0]	validation-mae:12406.76919
[1]	validation-mae:11689.57890
[2]	validation-mae:11053.01384
[3]	validation-mae:10514.12494
[4]	validation-mae:10037.70669
[5]	validation-mae:9620.05884
[6]	validation-mae:9253.46757
[7]	validation-mae:8936.26320
[8]	validation-mae:8677.26168
[9]	validation-mae:8429.37752

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12434.27688
[0]	validation-mae:12460.16138
[0]	validation-mae:12563.46374
[0]	validation-mae:12458.27472
[0]	validation-mae:12483.19453
[0]	validation-mae:12470.12918
[0]	validation-mae:12427.83161
[0]	validation-mae:12455.57341
[0]	validation-mae:12428.78723
[0]	validation-mae:12443.08584
[0]	validation-mae:12457.29329
[0]	validation-mae:12456.89916
[0]	validation-mae:12457.39298
[0]	validation-mae:12491.79192
[0]	validation-mae:12441.14881
[0]	validation-mae:12470.35241
[0]	validation-mae:12605.52902
[0]	validation-mae:12451.46518
[0]	validation-mae:12412.97215
[1]	validation-mae:11695.36010
[2]	validation-mae:11055.55650
[3]	validation-mae:10528.75199
[4]	validation-mae:10054.05482
[5]	validation-mae:9627.67946
[6]	validation-mae:9257.91786
[7]	validation-mae:8939.67732
[8]	validation-mae:8679.56069
[9]	validation-mae:8426.17919

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12482.03832
[0]	validation-mae:12428.40805
[0]	validation-mae:12411.49138
[1]	validation-mae:11691.96772
[2]	validation-mae:11062.03353
[3]	validation-mae:10522.15476
[4]	validation-mae:10039.95963
[5]	validation-mae:9614.31706
[6]	validation-mae:9263.10606
[7]	validation-mae:8966.17572
[8]	validation-mae:8693.30516
[9]	validation-mae:8442.59901

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12445.68298
[0]	validation-mae:12431.09144
[0]	validation-mae:13151.83073
[0]	validation-mae:12407.51242
[1]	validation-mae:11688.39036
[2]	validation-mae:11051.81491
[3]	validation-mae:10518.75172
[4]	validation-mae:10042.01677
[5]	validation-mae:9619.86069
[6]	validation-mae:9253.45528
[7]	validation-mae:8944.43192
[8]	validation-mae:8694.03744
[9]	validation-mae:8448.50835

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12483.55633
[0]	validation-mae:12470.10981
[0]	validation-mae:12433.54248
[0]	validation-mae:12484.71579
[0]	validation-mae:12441.40160
[0]	validation-mae:12410.12983
[1]	validation-mae:11692.64271
[2]	validation-mae:11061.73862
[3]	validation-mae:10530.74453
[4]	validation-mae:10055.26363
[5]	validation-mae:9633.89894
[6]	validation-mae:9260.12521
[7]	validation-mae:8952.13402
[8]	validation-mae:8695.92586
[9]	validation-mae:8443.36524

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12418.91344
[1]	validation-mae:11695.01573
[2]	validation-mae:11069.14259
[3]	validation-mae:10539.89612
[4]	validation-mae:10073.01944
[0]	validation-mae:12441.14613
[0]	validation-mae:12475.31282
[0]	validation-mae:12516.48306
[0]	validation-mae:12411.84614
[1]	validation-mae:11691.67716
[2]	validation-mae:11061.56748
[3]	validation-mae:10523.15128
[4]	validation-mae:10048.88862
[5]	validation-mae:9621.10629
[6]	validation-mae:9251.62049
[7]	validation-mae:8949.66858
[8]	validation-mae:8672.06828
[9]	validation-mae:8416.43135

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12431.97969
[0]	validation-mae:12426.31669
[0]	validation-mae:12434.41632
[0]	validation-mae:12418.22505
[1]	validation-mae:11698.45641
[2]	validation-mae:11078.50953
[3]	validation-mae:10540.06694
[4]	validation-mae:10064.83295
[5]	validation-mae:9641.00769
[6]	validation-mae:9273.32849
[7]	validation-mae:8966.87361
[8]	validation-mae:8679.58192
[9]	validation-mae:8427.12246

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12747.93232
[0]	validation-mae:12442.25883
[0]	validation-mae:12506.98463
[0]	validation-mae:12433.67780
[0]	validation-mae:12427.94226
[0]	validation-mae:12414.79711
[1]	validation-mae:11693.30707
[2]	validation-mae:11056.51106
[3]	validation-mae:10520.98226
[4]	validation-mae:10044.28724
[5]	validation-mae:9617.04611
[6]	validation-mae:9243.23098
[7]	validation-mae:8944.14612
[8]	validation-mae:8675.62754
[9]	validation-mae:8415.79380

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12481.78882
[0]	validation-mae:12414.73206
[1]	validation-mae:11694.49666
[2]	validation-mae:11067.51779
[3]	validation-mae:10529.09126
[4]	validation-mae:10052.37974
[5]	validation-mae:9627.20814
[6]	validation-mae:9258.09555
[7]	validation-mae:8956.29817
[8]	validation-mae:8674.58246
[9]	validation-mae:8423.09014

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12482.00727
[0]	validation-mae:12415.10118
[1]	validation-mae:11693.72374
[2]	validation-mae:11057.23010
[3]	validation-mae:10517.75261
[4]	validation-mae:10036.01398
[5]	validation-mae:9616.01462
[6]	validation-mae:9237.90944
[7]	validation-mae:8941.44688
[8]	validation-mae:8664.23636
[9]	validation-mae:8408.23191

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12486.92030
[0]	validation-mae:12461.66256
[0]	validation-mae:12590.99350
[0]	validation-mae:12449.83433
[0]	validation-mae:12454.20972
[0]	validation-mae:12600.65483
[0]	validation-mae:12502.93927
[0]	validation-mae:12427.01856
[0]	validation-mae:12413.62284
[0]	validation-mae:12527.66002
[0]	validation-mae:12413.31297
[1]	validation-mae:11694.91092
[2]	validation-mae:11058.11689
[3]	validation-mae:10517.63071
[4]	validation-mae:10035.27244
[5]	validation-mae:9612.52821
[6]	validation-mae:9244.46410
[7]	validation-mae:8929.21613
[8]	validation-mae:8651.34845
[9]	validation-mae:8407.51248

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12444.57207
[0]	validation-mae:12468.24804
[0]	validation-mae:12461.18825
[0]	validation-mae:12444.11889
[0]	validation-mae:12439.77734
[0]	validation-mae:12412.57875
[1]	validation-mae:11697.59701
[2]	validation-mae:11065.23225
[3]	validation-mae:10529.96866
[4]	validation-mae:10039.09114
[5]	validation-mae:9616.24660
[6]	validation-mae:9253.94007
[7]	validation-mae:8952.78115
[8]	validation-mae:8674.21779
[9]	validation-mae:8417.75103

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12456.79500
[0]	validation-mae:12436.42948
[0]	validation-mae:12679.58956
[0]	validation-mae:12431.11566
[0]	validation-mae:12470.45936
[0]	validation-mae:12417.27680
[1]	validation-mae:11698.73077
[2]	validation-mae:11064.82957
[3]	validation-mae:10522.28523
[4]	validation-mae:10040.71740
[5]	validation-mae:9613.24675
[6]	validation-mae:9243.32020
[7]	validation-mae:8927.37680
[8]	validation-mae:8661.93723
[9]	validation-mae:8405.51687

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12662.37001
[0]	validation-mae:12414.78389
[1]	validation-mae:11697.46877
[2]	validation-mae:11059.01044
[3]	validation-mae:10526.64288
[4]	validation-mae:10047.13066
[5]	validation-mae:9620.63392
[6]	validation-mae:9249.70345
[7]	validation-mae:8941.01700
[8]	validation-mae:8684.87157
[9]	validation-mae:8423.18530

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12482.16573
[0]	validation-mae:12412.38932
[1]	validation-mae:11693.19154
[2]	validation-mae:11063.27120
[3]	validation-mae:10524.85350
[4]	validation-mae:10044.02073
[5]	validation-mae:9619.26358
[6]	validation-mae:9251.14223
[7]	validation-mae:8931.60833
[8]	validation-mae:8670.78405
[9]	validation-mae:8420.68760

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12472.17783
[0]	validation-mae:12455.45799
[0]	validation-mae:12461.62956
[0]	validation-mae:12703.98901
[0]	validation-mae:12428.47297
[0]	validation-mae:12435.77389
[0]	validation-mae:12483.51368
[0]	validation-mae:12456.16840
[0]	validation-mae:12430.19498
[0]	validation-mae:12445.22858
[0]	validation-mae:12416.22150
[1]	validation-mae:11698.15034
[2]	validation-mae:11067.45931
[3]	validation-mae:10528.08432
[4]	validation-mae:10050.84773
[5]	validation-mae:9628.59091
[6]	validation-mae:9259.38801
[7]	validation-mae:8941.80142
[8]	validation-mae:8678.29021
[9]	validation-mae:8439.95701

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12921.66079
[0]	validation-mae:12497.49327
[0]	validation-mae:13109.63925
[0]	validation-mae:12429.58708
[0]	validation-mae:12416.03613
[1]	validation-mae:11697.40036
[2]	validation-mae:11066.98294
[3]	validation-mae:10534.77868
[4]	validation-mae:10039.51261
[5]	validation-mae:9638.66379
[0]	validation-mae:12413.36959
[1]	validation-mae:11694.54072
[2]	validation-mae:11063.42736
[3]	validation-mae:10524.60401
[4]	validation-mae:10050.57560
[5]	validation-mae:9622.31172
[6]	validation-mae:9254.23621
[7]	validation-mae:8950.77533
[8]	validation-mae:8671.90439
[9]	validation-mae:8417.01914

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12547.07734
[0]	validation-mae:12426.22624
[0]	validation-mae:12407.45474
[1]	validation-mae:11694.92268
[2]	validation-mae:11065.42885
[3]	validation-mae:10513.44506
[4]	validation-mae:10020.42285
[5]	validation-mae:9627.80182
[6]	validation-mae:9271.89835
[7]	validation-mae:8971.07567
[8]	validation-mae:8708.95532
[0]	validation-mae:12495.44425
[0]	validation-mae:12487.28485
[0]	validation-mae:12655.81597
[0]	validation-mae:12415.96290
[1]	validation-mae:11690.62165
[2]	validation-mae:11054.00992
[3]	validation-mae:10513.90514
[4]	validation-mae:10029.06329
[5]	validation-mae:9602.40251
[6]	validation-mae:9249.61938
[7]	validation-mae:8942.00461
[8]	validation-mae:8669.43039
[9]	validation-mae:8419.89473

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12992.11466
[0]	validation-mae:12475.59414
[0]	validation-mae:12424.36695
[0]	validation-mae:12973.25745
[0]	validation-mae:12496.26860
[0]	validation-mae:12463.03996
[0]	validation-mae:12472.80865
[0]	validation-mae:12405.44782
[1]	validation-mae:11681.84267
[2]	validation-mae:11043.73706
[3]	validation-mae:10508.71030
[4]	validation-mae:10020.81959
[5]	validation-mae:9608.99057
[6]	validation-mae:9235.08454
[7]	validation-mae:8934.12382
[8]	validation-mae:8657.70335
[9]	validation-mae:8402.64358

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12464.10687
[0]	validation-mae:12447.75107
[0]	validation-mae:12406.38563
[1]	validation-mae:11679.46582
[2]	validation-mae:11040.71013
[3]	validation-mae:10506.70993
[4]	validation-mae:10014.16327
[5]	validation-mae:9596.75920
[6]	validation-mae:9240.11956
[7]	validation-mae:8941.96823
[8]	validation-mae:8677.90256
[9]	validation-mae:8431.37486

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12412.54689
[1]	validation-mae:11698.25811
[2]	validation-mae:11061.84516
[3]	validation-mae:10526.61571
[4]	validation-mae:10046.12213
[5]	validation-mae:9623.76401
[6]	validation-mae:9245.92721
[7]	validation-mae:8926.74038
[8]	validation-mae:8666.54732
[9]	validation-mae:8409.74553

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12452.79318
[0]	validation-mae:12520.38909
[0]	validation-mae:12427.47633
[0]	validation-mae:12545.99488
[0]	validation-mae:12424.25233
[0]	validation-mae:12760.02289
[0]	validation-mae:12445.19980
[0]	validation-mae:12421.77184
[0]	validation-mae:12460.39998
[0]	validation-mae:12436.94240
[0]	validation-mae:12412.47454
[1]	validation-mae:11695.50209
[2]	validation-mae:11059.41279
[3]	validation-mae:10523.32800
[4]	validation-mae:10044.11816
[5]	validation-mae:9619.56182
[6]	validation-mae:9245.93287
[7]	validation-mae:8949.60212
[8]	validation-mae:8679.59970
[9]	validation-mae:8429.69810

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12538.12725
[0]	validation-mae:12405.32556
[1]	validation-mae:11686.41538
[2]	validation-mae:11047.23583
[3]	validation-mae:10516.76352
[4]	validation-mae:10042.46065
[5]	validation-mae:9613.87519
[6]	validation-mae:9241.58064
[7]	validation-mae:8943.03172
[8]	validation-mae:8670.57187
[9]	validation-mae:8427.24130

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12516.00543
[0]	validation-mae:12480.91024
[0]	validation-mae:12412.05973
[1]	validation-mae:11695.80958
[2]	validation-mae:11057.47306
[3]	validation-mae:10521.86116
[4]	validation-mae:10038.36066
[5]	validation-mae:9609.79243
[6]	validation-mae:9233.63808
[7]	validation-mae:8944.85226
[8]	validation-mae:8681.86270
[9]	validation-mae:8434.51657

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12405.63724
[1]	validation-mae:11688.20780
[2]	validation-mae:11053.23722
[3]	validation-mae:10520.56826
[4]	validation-mae:10038.44388
[5]	validation-mae:9622.36401
[6]	validation-mae:9258.66362
[7]	validation-mae:8960.36240
[8]	validation-mae:8686.26386
[9]	validation-mae:8427.50340

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:12429.41353
[0]	validation-mae:12447.67192
[0]	validation-mae:12430.15195
[0]	validation-mae:12455.62800
[0]	validation-mae:12416.21153
[1]	validation-mae:11696.71634
[2]	validation-mae:11056.65105
[3]	validation-mae:10516.73839
[4]	validation-mae:10035.90280
[5]	validation-mae:9616.02728
[6]	validation-mae:9239.39218
[7]	validation-mae:8936.73336
[8]	validation-mae:8668.73374
[9]	validation-mae:8412.86607

/usr/local/lib/python3.10/dist-packages/optuna/trial/_trial.py:497: UserWarning: The reported value is ignored because this `step` 1 is already reported.
  warnings.warn(

[0]	validation-mae:13056.95170
[0]	validation-mae:12472.24181
[0]	validation-mae:12416.37252
[1]	validation-mae:11692.77681
[2]	validation-mae:11069.59227
[3]	validation-mae:10523.41480
[0]	validation-mae:12443.56981

In [132]:
#4:

print("Número de trials:", len(study.trials))
print("MEJOR MAE:", study.best_value)
print("Mejores hiperparámetros:", study.best_params)

Número de trials: 867
MEJOR MAE: 8295.530641767147
Mejores hiperparámetros: {'learning_rate': 0.09997253101991131, 'n_estimators': 411, 'max_depth': 8, 'max_leaves': 0, 'min_child_weight': 4, 'reg_alpha': 0.8212350405694226, 'reg_lambda': 0.385110921857438, 'min_frequency': 0.03395392955562982}

Al comparar con la anterior version de Optuna, sin prunning, se puede ver que los resultados no son mejores. Esto se debe a que mediante el prunning, se decide detener el entrenamiento del modelo si no hay mejorias en las metricas para evaluar el modelo, en nuestro caso, el MAE.

In [134]:
#5:

best_pipeline2 = study.user_attrs["best_pipeline"]
with open(file_path + '/best_xgb_pipeline2.pkl', 'wb') as f:
    pickle.dump(best_pipeline2, f)

## 5. Visualizaciones (5 puntos)

<p align="center">
  <img src="https://media.tenor.com/F-LgB1xTebEAAAAd/look-at-this-graph-nickelback.gif">
</p>


Satisfecho con su trabajo, Fiu le pregunta si es posible generar visualizaciones que permitan entender el entrenamiento de su modelo.

A partir del siguiente <a href = https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/005_visualization.html#visualization>enlace</a>, genere las siguientes visualizaciones:

1. Gráfico de historial de optimización [1 punto]
2. Gráfico de coordenadas paralelas [1 punto]
3. Gráfico de importancia de hiperparámetros [1 punto]

Comente sus resultados:

4. ¿Desde qué *trial* se empiezan a observar mejoras notables en sus resultados? [0.5 puntos]
5. ¿Qué tendencias puede observar a partir del gráfico de coordenadas paralelas? [1 punto]
6. ¿Cuáles son los hiperparámetros con mayor importancia para la optimización de su modelo? [0.5 puntos]

In [139]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision


import optuna

# You can use Matplotlib instead of Plotly for visualization by simply replacing `optuna.visualization` with
# `optuna.visualization.matplotlib` in the following examples.
from optuna.visualization import plot_contour
from optuna.visualization import plot_edf
from optuna.visualization import plot_intermediate_values
from optuna.visualization import plot_optimization_history
from optuna.visualization import plot_parallel_coordinate
from optuna.visualization import plot_param_importances
from optuna.visualization import plot_rank
from optuna.visualization import plot_slice
from optuna.visualization import plot_timeline


SEED = 13
torch.manual_seed(SEED)

DEVICE = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
DIR = ".."
BATCHSIZE = 128
N_TRAIN_EXAMPLES = BATCHSIZE * 30
N_VALID_EXAMPLES = BATCHSIZE * 10


def define_model(trial):
    n_layers = trial.suggest_int("n_layers", 1, 2)
    layers = []

    in_features = 28 * 28
    for i in range(n_layers):
        out_features = trial.suggest_int("n_units_l{}".format(i), 64, 512)
        layers.append(nn.Linear(in_features, out_features))
        layers.append(nn.ReLU())

        in_features = out_features

    layers.append(nn.Linear(in_features, 10))
    layers.append(nn.LogSoftmax(dim=1))

    return nn.Sequential(*layers)


# Defines training and evaluation.
def train_model(model, optimizer, train_loader):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.view(-1, 28 * 28).to(DEVICE), target.to(DEVICE)
        optimizer.zero_grad()
        F.nll_loss(model(data), target).backward()
        optimizer.step()


def eval_model(model, valid_loader):
    model.eval()
    correct = 0
    with torch.no_grad():
        for batch_idx, (data, target) in enumerate(valid_loader):
            data, target = data.view(-1, 28 * 28).to(DEVICE), target.to(DEVICE)
            pred = model(data).argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

    accuracy = correct / N_VALID_EXAMPLES

    return accuracy

In [140]:
def objective(trial):
    train_dataset = torchvision.datasets.FashionMNIST(
        DIR, train=True, download=True, transform=torchvision.transforms.ToTensor()
    )
    train_loader = torch.utils.data.DataLoader(
        torch.utils.data.Subset(train_dataset, list(range(N_TRAIN_EXAMPLES))),
        batch_size=BATCHSIZE,
        shuffle=True,
    )

    val_dataset = torchvision.datasets.FashionMNIST(
        DIR, train=False, transform=torchvision.transforms.ToTensor()
    )
    val_loader = torch.utils.data.DataLoader(
        torch.utils.data.Subset(val_dataset, list(range(N_VALID_EXAMPLES))),
        batch_size=BATCHSIZE,
        shuffle=True,
    )
    model = define_model(trial).to(DEVICE)

    optimizer = torch.optim.Adam(
        model.parameters(), trial.suggest_float("lr", 1e-5, 1e-1, log=True)
    )

    for epoch in range(10):
        train_model(model, optimizer, train_loader)

        val_accuracy = eval_model(model, val_loader)
        trial.report(val_accuracy, epoch)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return val_accuracy

In [141]:
plot_optimization_history(study)

Se ve que a partir del trial 11 el valor baja, por lo que los primeros trial son mejores.

In [142]:
plot_parallel_coordinate(study)

In [144]:
plot_param_importances(study)

## 6. Síntesis de resultados (3 puntos)

Finalmente:

1. Genere una tabla resumen del MAE en el conjunto de validación obtenido en los 5 modelos entrenados desde Baseline hasta XGBoost con Constraints, Optuna y Prunning. [1 punto]
2. Compare los resultados de la tabla y responda, ¿qué modelo obtiene el mejor rendimiento? [0.5 puntos]
3. Cargue el mejor modelo, prediga sobre el conjunto de **test** y reporte su MAE. [0.5 puntos]
4. ¿Existen diferencias con respecto a las métricas obtenidas en el conjunto de validación? ¿Porqué puede ocurrir esto? [1 punto]

# Conclusión
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://media.tenor.com/8CT1AXElF_cAAAAC/gojo-satoru.gif">
</p>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>